/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HNTAS.Api.Client.Model;
using HNTAS.Api.Client.Client;
using System.Reflection;

namespace HNTAS.Api.Client.Test.Model
{
    /// <summary>
<<<<<<<< HEAD:HNTAS/HNTAS.Api.Client/src/HNTAS.Api.Client.Test/Model/ConnectionTypeTests.cs
    ///  Class for testing ConnectionType
========
    ///  Class for testing AssessmentPlanStatus
>>>>>>>> f05028e74d3945e17c6e4dc0a284b52f6b8ade65:HNTAS/HNTAS.Api.Client/src/HNTAS.Api.Client.Test/Model/AssessmentPlanStatusTests.cs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
<<<<<<<< HEAD:HNTAS/HNTAS.Api.Client/src/HNTAS.Api.Client.Test/Model/ConnectionTypeTests.cs
    public class ConnectionTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConnectionType
        //private ConnectionType instance;

        public ConnectionTypeTests()
        {
            // TODO uncomment below to create an instance of ConnectionType
            //instance = new ConnectionType();
========
    public class AssessmentPlanStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssessmentPlanStatus
        //private AssessmentPlanStatus instance;

        public AssessmentPlanStatusTests()
        {
            // TODO uncomment below to create an instance of AssessmentPlanStatus
            //instance = new AssessmentPlanStatus();
>>>>>>>> f05028e74d3945e17c6e4dc0a284b52f6b8ade65:HNTAS/HNTAS.Api.Client/src/HNTAS.Api.Client.Test/Model/AssessmentPlanStatusTests.cs
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
<<<<<<<< HEAD:HNTAS/HNTAS.Api.Client/src/HNTAS.Api.Client.Test/Model/ConnectionTypeTests.cs
        /// Test an instance of ConnectionType
        /// </summary>
        [Fact]
        public void ConnectionTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConnectionType
            //Assert.IsType<ConnectionType>(instance);
========
        /// Test an instance of AssessmentPlanStatus
        /// </summary>
        [Fact]
        public void AssessmentPlanStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" AssessmentPlanStatus
            //Assert.IsType<AssessmentPlanStatus>(instance);
>>>>>>>> f05028e74d3945e17c6e4dc0a284b52f6b8ade65:HNTAS/HNTAS.Api.Client/src/HNTAS.Api.Client.Test/Model/AssessmentPlanStatusTests.cs
        }
    }
}
