/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HNTAS.Api.Client.Model;
using HNTAS.Api.Client.Client;
using System.Reflection;

namespace HNTAS.Api.Client.Test.Model
{
    /// <summary>
    ///  Class for testing AssignedAssessorRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssignedAssessorRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssignedAssessorRequest
        //private AssignedAssessorRequest instance;

        public AssignedAssessorRequestTests()
        {
            // TODO uncomment below to create an instance of AssignedAssessorRequest
            //instance = new AssignedAssessorRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssignedAssessorRequest
        /// </summary>
        [Fact]
        public void AssignedAssessorRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AssignedAssessorRequest
            //Assert.IsType<AssignedAssessorRequest>(instance);
        }

        /// <summary>
        /// Test the property 'SortBy'
        /// </summary>
        [Fact]
        public void SortByTest()
        {
            // TODO unit test for the property 'SortBy'
        }

        /// <summary>
        /// Test the property 'SortDirection'
        /// </summary>
        [Fact]
        public void SortDirectionTest()
        {
            // TODO unit test for the property 'SortDirection'
        }

        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }

        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }
    }
}
