/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HNTAS.Api.Client.Model;
using HNTAS.Api.Client.Client;
using System.Reflection;

namespace HNTAS.Api.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DistributionNetworksAndSubstations
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DistributionNetworksAndSubstationsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DistributionNetworksAndSubstations
        //private DistributionNetworksAndSubstations instance;

        public DistributionNetworksAndSubstationsTests()
        {
            // TODO uncomment below to create an instance of DistributionNetworksAndSubstations
            //instance = new DistributionNetworksAndSubstations();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DistributionNetworksAndSubstations
        /// </summary>
        [Fact]
        public void DistributionNetworksAndSubstationsInstanceTest()
        {
            // TODO uncomment below to test "IsType" DistributionNetworksAndSubstations
            //Assert.IsType<DistributionNetworksAndSubstations>(instance);
        }

        /// <summary>
        /// Test the property 'IsAnyDistrictSubstations'
        /// </summary>
        [Fact]
        public void IsAnyDistrictSubstationsTest()
        {
            // TODO unit test for the property 'IsAnyDistrictSubstations'
        }

        /// <summary>
        /// Test the property 'NumberOfSubstations'
        /// </summary>
        [Fact]
        public void NumberOfSubstationsTest()
        {
            // TODO unit test for the property 'NumberOfSubstations'
        }

        /// <summary>
        /// Test the property 'NumberOfDistributionNetworks'
        /// </summary>
        [Fact]
        public void NumberOfDistributionNetworksTest()
        {
            // TODO unit test for the property 'NumberOfDistributionNetworks'
        }
    }
}
