/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HNTAS.Api.Client.Model;
using HNTAS.Api.Client.Client;
using System.Reflection;

namespace HNTAS.Api.Client.Test.Model
{
    /// <summary>
    ///  Class for testing HeatNetworkConnections2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HeatNetworkConnections2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HeatNetworkConnections2
        //private HeatNetworkConnections2 instance;

        public HeatNetworkConnections2Tests()
        {
            // TODO uncomment below to create an instance of HeatNetworkConnections2
            //instance = new HeatNetworkConnections2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HeatNetworkConnections2
        /// </summary>
        [Fact]
        public void HeatNetworkConnections2InstanceTest()
        {
            // TODO uncomment below to test "IsType" HeatNetworkConnections2
            //Assert.IsType<HeatNetworkConnections2>(instance);
        }

        /// <summary>
        /// Test the property 'IsCommunalBuilding'
        /// </summary>
        [Fact]
        public void IsCommunalBuildingTest()
        {
            // TODO unit test for the property 'IsCommunalBuilding'
        }

        /// <summary>
        /// Test the property 'NoOfCommunalBuilding'
        /// </summary>
        [Fact]
        public void NoOfCommunalBuildingTest()
        {
            // TODO unit test for the property 'NoOfCommunalBuilding'
        }

        /// <summary>
        /// Test the property 'IsDomesticConsumer'
        /// </summary>
        [Fact]
        public void IsDomesticConsumerTest()
        {
            // TODO unit test for the property 'IsDomesticConsumer'
        }

        /// <summary>
        /// Test the property 'NoOfDomesticConsumer'
        /// </summary>
        [Fact]
        public void NoOfDomesticConsumerTest()
        {
            // TODO unit test for the property 'NoOfDomesticConsumer'
        }

        /// <summary>
        /// Test the property 'IsNonDomesticConsumer'
        /// </summary>
        [Fact]
        public void IsNonDomesticConsumerTest()
        {
            // TODO unit test for the property 'IsNonDomesticConsumer'
        }

        /// <summary>
        /// Test the property 'NoOfNonDomesticConsumer'
        /// </summary>
        [Fact]
        public void NoOfNonDomesticConsumerTest()
        {
            // TODO unit test for the property 'NoOfNonDomesticConsumer'
        }

        /// <summary>
        /// Test the property 'IsOtherDistrictNetwork'
        /// </summary>
        [Fact]
        public void IsOtherDistrictNetworkTest()
        {
            // TODO unit test for the property 'IsOtherDistrictNetwork'
        }

        /// <summary>
        /// Test the property 'NoOfOtherDistrictNetworks'
        /// </summary>
        [Fact]
        public void NoOfOtherDistrictNetworksTest()
        {
            // TODO unit test for the property 'NoOfOtherDistrictNetworks'
        }

        /// <summary>
        /// Test the property 'NoOfOtherDistrictNetwork'
        /// </summary>
        [Fact]
        public void NoOfOtherDistrictNetworkTest()
        {
            // TODO unit test for the property 'NoOfOtherDistrictNetwork'
        }
    }
}
