/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HNTAS.Api.Client.Model;
using HNTAS.Api.Client.Client;
using System.Reflection;

namespace HNTAS.Api.Client.Test.Model
{
    /// <summary>
    ///  Class for testing HnRoleMappingsUserResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HnRoleMappingsUserResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HnRoleMappingsUserResult
        //private HnRoleMappingsUserResult instance;

        public HnRoleMappingsUserResultTests()
        {
            // TODO uncomment below to create an instance of HnRoleMappingsUserResult
            //instance = new HnRoleMappingsUserResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HnRoleMappingsUserResult
        /// </summary>
        [Fact]
        public void HnRoleMappingsUserResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" HnRoleMappingsUserResult
            //Assert.IsType<HnRoleMappingsUserResult>(instance);
        }

        /// <summary>
        /// Test the property 'HeatNetwork'
        /// </summary>
        [Fact]
        public void HeatNetworkTest()
        {
            // TODO unit test for the property 'HeatNetwork'
        }

        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Fact]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }
    }
}
