/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HNTAS.Api.Client.Model;
using HNTAS.Api.Client.Client;
using System.Reflection;

namespace HNTAS.Api.Client.Test.Model
{
    /// <summary>
    ///  Class for testing JourneyDataResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JourneyDataResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JourneyDataResponse
        //private JourneyDataResponse instance;

        public JourneyDataResponseTests()
        {
            // TODO uncomment below to create an instance of JourneyDataResponse
            //instance = new JourneyDataResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JourneyDataResponse
        /// </summary>
        [Fact]
        public void JourneyDataResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" JourneyDataResponse
            //Assert.IsType<JourneyDataResponse>(instance);
        }

        /// <summary>
        /// Test the property 'NetworkType'
        /// </summary>
        [Fact]
        public void NetworkTypeTest()
        {
            // TODO unit test for the property 'NetworkType'
        }

        /// <summary>
        /// Test the property 'ConnectionTypes'
        /// </summary>
        [Fact]
        public void ConnectionTypesTest()
        {
            // TODO unit test for the property 'ConnectionTypes'
        }

        /// <summary>
        /// Test the property 'HeatNetworkElements'
        /// </summary>
        [Fact]
        public void HeatNetworkElementsTest()
        {
            // TODO unit test for the property 'HeatNetworkElements'
        }

        /// <summary>
        /// Test the property 'AssessmentPlans'
        /// </summary>
        [Fact]
        public void AssessmentPlansTest()
        {
            // TODO unit test for the property 'AssessmentPlans'
        }
    }
}
