/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HNTAS.Api.Client.Model;
using HNTAS.Api.Client.Client;
using System.Reflection;

namespace HNTAS.Api.Client.Test.Model
{
    /// <summary>
    ///  Class for testing KpiConfigRequestV2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KpiConfigRequestV2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for KpiConfigRequestV2
        //private KpiConfigRequestV2 instance;

        public KpiConfigRequestV2Tests()
        {
            // TODO uncomment below to create an instance of KpiConfigRequestV2
            //instance = new KpiConfigRequestV2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KpiConfigRequestV2
        /// </summary>
        [Fact]
        public void KpiConfigRequestV2InstanceTest()
        {
            // TODO uncomment below to test "IsType" KpiConfigRequestV2
            //Assert.IsType<KpiConfigRequestV2>(instance);
        }

        /// <summary>
        /// Test the property 'NetworkId'
        /// </summary>
        [Fact]
        public void NetworkIdTest()
        {
            // TODO unit test for the property 'NetworkId'
        }

        /// <summary>
        /// Test the property 'Elements'
        /// </summary>
        [Fact]
        public void ElementsTest()
        {
            // TODO unit test for the property 'Elements'
        }

        /// <summary>
        /// Test the property 'CarbonCalculator'
        /// </summary>
        [Fact]
        public void CarbonCalculatorTest()
        {
            // TODO unit test for the property 'CarbonCalculator'
        }
    }
}
