/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HNTAS.Api.Client.Model;
using HNTAS.Api.Client.Client;
using System.Reflection;

namespace HNTAS.Api.Client.Test.Model
{
    /// <summary>
    ///  Class for testing NetworkElementsStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NetworkElementsStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NetworkElementsStatus
        //private NetworkElementsStatus instance;

        public NetworkElementsStatusTests()
        {
            // TODO uncomment below to create an instance of NetworkElementsStatus
            //instance = new NetworkElementsStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NetworkElementsStatus
        /// </summary>
        [Fact]
        public void NetworkElementsStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" NetworkElementsStatus
            //Assert.IsType<NetworkElementsStatus>(instance);
        }
    }
}
