/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HNTAS.Api.Client.Model;
using HNTAS.Api.Client.Client;
using System.Reflection;

namespace HNTAS.Api.Client.Test.Model
{
    /// <summary>
    ///  Class for testing NetworkElementRequestV2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NetworkElementRequestV2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NetworkElementRequestV2
        //private NetworkElementRequestV2 instance;

        public NetworkElementRequestV2Tests()
        {
            // TODO uncomment below to create an instance of NetworkElementRequestV2
            //instance = new NetworkElementRequestV2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NetworkElementRequestV2
        /// </summary>
        [Fact]
        public void NetworkElementRequestV2InstanceTest()
        {
            // TODO uncomment below to test "IsType" NetworkElementRequestV2
            //Assert.IsType<NetworkElementRequestV2>(instance);
        }

        /// <summary>
        /// Test the property 'ElementId'
        /// </summary>
        [Fact]
        public void ElementIdTest()
        {
            // TODO unit test for the property 'ElementId'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Kpis'
        /// </summary>
        [Fact]
        public void KpisTest()
        {
            // TODO unit test for the property 'Kpis'
        }

        /// <summary>
        /// Test the property 'CarbonCalculatorInputs'
        /// </summary>
        [Fact]
        public void CarbonCalculatorInputsTest()
        {
            // TODO unit test for the property 'CarbonCalculatorInputs'
        }
    }
}
