/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HNTAS.Api.Client.Model;
using HNTAS.Api.Client.Client;
using System.Reflection;

namespace HNTAS.Api.Client.Test.Model
{
    /// <summary>
    ///  Class for testing NetworkDetailsUploadDocumentRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NetworkDetailsUploadDocumentRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NetworkDetailsUploadDocumentRequest
        //private NetworkDetailsUploadDocumentRequest instance;

        public NetworkDetailsUploadDocumentRequestTests()
        {
            // TODO uncomment below to create an instance of NetworkDetailsUploadDocumentRequest
            //instance = new NetworkDetailsUploadDocumentRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NetworkDetailsUploadDocumentRequest
        /// </summary>
        [Fact]
        public void NetworkDetailsUploadDocumentRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" NetworkDetailsUploadDocumentRequest
            //Assert.IsType<NetworkDetailsUploadDocumentRequest>(instance);
        }

        /// <summary>
        /// Test the property 'HnId'
        /// </summary>
        [Fact]
        public void HnIdTest()
        {
            // TODO unit test for the property 'HnId'
        }

        /// <summary>
        /// Test the property 'UploadedBy'
        /// </summary>
        [Fact]
        public void UploadedByTest()
        {
            // TODO unit test for the property 'UploadedBy'
        }

        /// <summary>
        /// Test the property 'FileName'
        /// </summary>
        [Fact]
        public void FileNameTest()
        {
            // TODO unit test for the property 'FileName'
        }

        /// <summary>
        /// Test the property 'S3Key'
        /// </summary>
        [Fact]
        public void S3KeyTest()
        {
            // TODO unit test for the property 'S3Key'
        }

        /// <summary>
        /// Test the property 'DocumentType'
        /// </summary>
        [Fact]
        public void DocumentTypeTest()
        {
            // TODO unit test for the property 'DocumentType'
        }
    }
}
