/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HNTAS.Api.Client.Model;
using HNTAS.Api.Client.Client;
using System.Reflection;

namespace HNTAS.Api.Client.Test.Model
{
    /// <summary>
    ///  Class for testing OrganisationDetailResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrganisationDetailResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrganisationDetailResult
        //private OrganisationDetailResult instance;

        public OrganisationDetailResultTests()
        {
            // TODO uncomment below to create an instance of OrganisationDetailResult
            //instance = new OrganisationDetailResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrganisationDetailResult
        /// </summary>
        [Fact]
        public void OrganisationDetailResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrganisationDetailResult
            //Assert.IsType<OrganisationDetailResult>(instance);
        }

        /// <summary>
        /// Test the property 'OrgId'
        /// </summary>
        [Fact]
        public void OrgIdTest()
        {
            // TODO unit test for the property 'OrgId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'CompaniesHouseNumber'
        /// </summary>
        [Fact]
        public void CompaniesHouseNumberTest()
        {
            // TODO unit test for the property 'CompaniesHouseNumber'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'RegisteredAddress'
        /// </summary>
        [Fact]
        public void RegisteredAddressTest()
        {
            // TODO unit test for the property 'RegisteredAddress'
        }

        /// <summary>
        /// Test the property 'HeatNetworks'
        /// </summary>
        [Fact]
        public void HeatNetworksTest()
        {
            // TODO unit test for the property 'HeatNetworks'
        }
    }
}
