/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HNTAS.Api.Client.Model;
using HNTAS.Api.Client.Client;
using System.Reflection;

namespace HNTAS.Api.Client.Test.Model
{
    /// <summary>
    ///  Class for testing RegisteredAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RegisteredAddressTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RegisteredAddress
        //private RegisteredAddress instance;

        public RegisteredAddressTests()
        {
            // TODO uncomment below to create an instance of RegisteredAddress
            //instance = new RegisteredAddress();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RegisteredAddress
        /// </summary>
        [Fact]
        public void RegisteredAddressInstanceTest()
        {
            // TODO uncomment below to test "IsType" RegisteredAddress
            //Assert.IsType<RegisteredAddress>(instance);
        }

        /// <summary>
        /// Test the property 'AddressLine1'
        /// </summary>
        [Fact]
        public void AddressLine1Test()
        {
            // TODO unit test for the property 'AddressLine1'
        }

        /// <summary>
        /// Test the property 'Postcode'
        /// </summary>
        [Fact]
        public void PostcodeTest()
        {
            // TODO unit test for the property 'Postcode'
        }

        /// <summary>
        /// Test the property 'AddressLine2'
        /// </summary>
        [Fact]
        public void AddressLine2Test()
        {
            // TODO unit test for the property 'AddressLine2'
        }

        /// <summary>
        /// Test the property 'Town'
        /// </summary>
        [Fact]
        public void TownTest()
        {
            // TODO unit test for the property 'Town'
        }

        /// <summary>
        /// Test the property 'County'
        /// </summary>
        [Fact]
        public void CountyTest()
        {
            // TODO unit test for the property 'County'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
    }
}
