/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HNTAS.Api.Client.Model;
using HNTAS.Api.Client.Client;
using System.Reflection;

namespace HNTAS.Api.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SoaStages
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SoaStagesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SoaStages
        //private SoaStages instance;

        public SoaStagesTests()
        {
            // TODO uncomment below to create an instance of SoaStages
            //instance = new SoaStages();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SoaStages
        /// </summary>
        [Fact]
        public void SoaStagesInstanceTest()
        {
            // TODO uncomment below to test "IsType" SoaStages
            //Assert.IsType<SoaStages>(instance);
        }

        /// <summary>
        /// Test the property 'Stage'
        /// </summary>
        [Fact]
        public void StageTest()
        {
            // TODO unit test for the property 'Stage'
        }

        /// <summary>
        /// Test the property 'Elements'
        /// </summary>
        [Fact]
        public void ElementsTest()
        {
            // TODO unit test for the property 'Elements'
        }
    }
}
