/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HNTAS.Api.Client.Model;
using HNTAS.Api.Client.Client;
using System.Reflection;

namespace HNTAS.Api.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SoaStatusWithCount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SoaStatusWithCountTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SoaStatusWithCount
        //private SoaStatusWithCount instance;

        public SoaStatusWithCountTests()
        {
            // TODO uncomment below to create an instance of SoaStatusWithCount
            //instance = new SoaStatusWithCount();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SoaStatusWithCount
        /// </summary>
        [Fact]
        public void SoaStatusWithCountInstanceTest()
        {
            // TODO uncomment below to test "IsType" SoaStatusWithCount
            //Assert.IsType<SoaStatusWithCount>(instance);
        }

        /// <summary>
        /// Test the property 'SoaStatusType'
        /// </summary>
        [Fact]
        public void SoaStatusTypeTest()
        {
            // TODO unit test for the property 'SoaStatusType'
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
    }
}
