/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HNTAS.Api.Client.Model;
using HNTAS.Api.Client.Client;
using System.Reflection;

namespace HNTAS.Api.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SoaStatusWithCountExistingNetwork
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SoaStatusWithCountExistingNetworkTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SoaStatusWithCountExistingNetwork
        //private SoaStatusWithCountExistingNetwork instance;

        public SoaStatusWithCountExistingNetworkTests()
        {
            // TODO uncomment below to create an instance of SoaStatusWithCountExistingNetwork
            //instance = new SoaStatusWithCountExistingNetwork();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SoaStatusWithCountExistingNetwork
        /// </summary>
        [Fact]
        public void SoaStatusWithCountExistingNetworkInstanceTest()
        {
            // TODO uncomment below to test "IsType" SoaStatusWithCountExistingNetwork
            //Assert.IsType<SoaStatusWithCountExistingNetwork>(instance);
        }

        /// <summary>
        /// Test the property 'SoaStatus'
        /// </summary>
        [Fact]
        public void SoaStatusTest()
        {
            // TODO unit test for the property 'SoaStatus'
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
    }
}
