/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HNTAS.Api.Client.Model;
using HNTAS.Api.Client.Client;
using System.Reflection;

namespace HNTAS.Api.Client.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateConnectionsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateConnectionsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateConnectionsRequest
        //private UpdateConnectionsRequest instance;

        public UpdateConnectionsRequestTests()
        {
            // TODO uncomment below to create an instance of UpdateConnectionsRequest
            //instance = new UpdateConnectionsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateConnectionsRequest
        /// </summary>
        [Fact]
        public void UpdateConnectionsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateConnectionsRequest
            //Assert.IsType<UpdateConnectionsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'HnId'
        /// </summary>
        [Fact]
        public void HnIdTest()
        {
            // TODO unit test for the property 'HnId'
        }

        /// <summary>
        /// Test the property 'UpdatedBy'
        /// </summary>
        [Fact]
        public void UpdatedByTest()
        {
            // TODO unit test for the property 'UpdatedBy'
        }

        /// <summary>
        /// Test the property 'ConnectionTypes'
        /// </summary>
        [Fact]
        public void ConnectionTypesTest()
        {
            // TODO unit test for the property 'ConnectionTypes'
        }
    }
}
