/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HNTAS.Api.Client.Model;
using HNTAS.Api.Client.Client;
using System.Reflection;

namespace HNTAS.Api.Client.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateUserOrganisationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateUserOrganisationRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateUserOrganisationRequest
        //private UpdateUserOrganisationRequest instance;

        public UpdateUserOrganisationRequestTests()
        {
            // TODO uncomment below to create an instance of UpdateUserOrganisationRequest
            //instance = new UpdateUserOrganisationRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateUserOrganisationRequest
        /// </summary>
        [Fact]
        public void UpdateUserOrganisationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateUserOrganisationRequest
            //Assert.IsType<UpdateUserOrganisationRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Organisation'
        /// </summary>
        [Fact]
        public void OrganisationTest()
        {
            // TODO unit test for the property 'Organisation'
        }

        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Fact]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }

        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }

        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }

        /// <summary>
        /// Test the property 'JobTitle'
        /// </summary>
        [Fact]
        public void JobTitleTest()
        {
            // TODO unit test for the property 'JobTitle'
        }

        /// <summary>
        /// Test the property 'PreferredContactType'
        /// </summary>
        [Fact]
        public void PreferredContactTypeTest()
        {
            // TODO unit test for the property 'PreferredContactType'
        }

        /// <summary>
        /// Test the property 'LandlineNumber'
        /// </summary>
        [Fact]
        public void LandlineNumberTest()
        {
            // TODO unit test for the property 'LandlineNumber'
        }

        /// <summary>
        /// Test the property 'ContactNumberExtension'
        /// </summary>
        [Fact]
        public void ContactNumberExtensionTest()
        {
            // TODO unit test for the property 'ContactNumberExtension'
        }

        /// <summary>
        /// Test the property 'MobileNumber'
        /// </summary>
        [Fact]
        public void MobileNumberTest()
        {
            // TODO unit test for the property 'MobileNumber'
        }
    }
}
