/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HNTAS.Api.Client.Model;
using HNTAS.Api.Client.Client;
using System.Reflection;

namespace HNTAS.Api.Client.Test.Model
{
    /// <summary>
    ///  Class for testing UploadedAssessmentDocumentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UploadedAssessmentDocumentResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UploadedAssessmentDocumentResponse
        //private UploadedAssessmentDocumentResponse instance;

        public UploadedAssessmentDocumentResponseTests()
        {
            // TODO uncomment below to create an instance of UploadedAssessmentDocumentResponse
            //instance = new UploadedAssessmentDocumentResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UploadedAssessmentDocumentResponse
        /// </summary>
        [Fact]
        public void UploadedAssessmentDocumentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" UploadedAssessmentDocumentResponse
            //Assert.IsType<UploadedAssessmentDocumentResponse>(instance);
        }

        /// <summary>
        /// Test the property 'FileName'
        /// </summary>
        [Fact]
        public void FileNameTest()
        {
            // TODO unit test for the property 'FileName'
        }

        /// <summary>
        /// Test the property 'S3Key'
        /// </summary>
        [Fact]
        public void S3KeyTest()
        {
            // TODO unit test for the property 'S3Key'
        }

        /// <summary>
        /// Test the property 'Phase'
        /// </summary>
        [Fact]
        public void PhaseTest()
        {
            // TODO unit test for the property 'Phase'
        }

        /// <summary>
        /// Test the property 'Stage'
        /// </summary>
        [Fact]
        public void StageTest()
        {
            // TODO unit test for the property 'Stage'
        }

        /// <summary>
        /// Test the property 'UploadedAt'
        /// </summary>
        [Fact]
        public void UploadedAtTest()
        {
            // TODO unit test for the property 'UploadedAt'
        }

        /// <summary>
        /// Test the property 'UploadedBy'
        /// </summary>
        [Fact]
        public void UploadedByTest()
        {
            // TODO unit test for the property 'UploadedBy'
        }
    }
}
