/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HNTAS.Api.Client.Model;
using HNTAS.Api.Client.Client;
using System.Reflection;

namespace HNTAS.Api.Client.Test.Model
{
    /// <summary>
    ///  Class for testing UserRoleDetailResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserRoleDetailResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserRoleDetailResponse
        //private UserRoleDetailResponse instance;

        public UserRoleDetailResponseTests()
        {
            // TODO uncomment below to create an instance of UserRoleDetailResponse
            //instance = new UserRoleDetailResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserRoleDetailResponse
        /// </summary>
        [Fact]
        public void UserRoleDetailResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserRoleDetailResponse
            //Assert.IsType<UserRoleDetailResponse>(instance);
        }

        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Fact]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'EmailId'
        /// </summary>
        [Fact]
        public void EmailIdTest()
        {
            // TODO unit test for the property 'EmailId'
        }

        /// <summary>
        /// Test the property 'RoleDescription'
        /// </summary>
        [Fact]
        public void RoleDescriptionTest()
        {
            // TODO unit test for the property 'RoleDescription'
        }
    }
}
