// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// AuditLogResponse
    /// </summary>
    public partial class AuditLogResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuditLogResponse" /> class.
        /// </summary>
        /// <param name="entryType">entryType</param>
        /// <param name="userName">userName</param>
        /// <param name="role">role</param>
        /// <param name="timestamp">timestamp</param>
        /// <param name="elementName">elementName</param>
        /// <param name="phase">phase</param>
        /// <param name="stage">stage</param>
        [JsonConstructor]
        public AuditLogResponse(Option<string?> entryType = default, Option<string?> userName = default, Option<string?> role = default, Option<string?> timestamp = default, Option<string?> elementName = default, Option<string?> phase = default, Option<string?> stage = default)
        {
            EntryTypeOption = entryType;
            UserNameOption = userName;
            RoleOption = role;
            TimestampOption = timestamp;
            ElementNameOption = elementName;
            PhaseOption = phase;
            StageOption = stage;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of EntryType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EntryTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets EntryType
        /// </summary>
        [JsonPropertyName("entryType")]
        public string? EntryType { get { return this.EntryTypeOption; } set { this.EntryTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of UserName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UserNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets UserName
        /// </summary>
        [JsonPropertyName("userName")]
        public string? UserName { get { return this.UserNameOption; } set { this.UserNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Role
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RoleOption { get; private set; }

        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        [JsonPropertyName("role")]
        public string? Role { get { return this.RoleOption; } set { this.RoleOption = new(value); } }

        /// <summary>
        /// Used to track the state of Timestamp
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TimestampOption { get; private set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [JsonPropertyName("timestamp")]
        public string? Timestamp { get { return this.TimestampOption; } set { this.TimestampOption = new(value); } }

        /// <summary>
        /// Used to track the state of ElementName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ElementNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets ElementName
        /// </summary>
        [JsonPropertyName("elementName")]
        public string? ElementName { get { return this.ElementNameOption; } set { this.ElementNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Phase
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PhaseOption { get; private set; }

        /// <summary>
        /// Gets or Sets Phase
        /// </summary>
        [JsonPropertyName("phase")]
        public string? Phase { get { return this.PhaseOption; } set { this.PhaseOption = new(value); } }

        /// <summary>
        /// Used to track the state of Stage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Stage
        /// </summary>
        [JsonPropertyName("stage")]
        public string? Stage { get { return this.StageOption; } set { this.StageOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuditLogResponse {\n");
            sb.Append("  EntryType: ").Append(EntryType).Append("\n");
            sb.Append("  UserName: ").Append(UserName).Append("\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  ElementName: ").Append(ElementName).Append("\n");
            sb.Append("  Phase: ").Append(Phase).Append("\n");
            sb.Append("  Stage: ").Append(Stage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AuditLogResponse" />
    /// </summary>
    public class AuditLogResponseJsonConverter : JsonConverter<AuditLogResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="AuditLogResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AuditLogResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> entryType = default;
            Option<string?> userName = default;
            Option<string?> role = default;
            Option<string?> timestamp = default;
            Option<string?> elementName = default;
            Option<string?> phase = default;
            Option<string?> stage = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "entryType":
                            entryType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "userName":
                            userName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "role":
                            role = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "timestamp":
                            timestamp = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "elementName":
                            elementName = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "phase":
                            phase = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "stage":
                            stage = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (entryType.IsSet && entryType.Value == null)
                throw new ArgumentNullException(nameof(entryType), "Property is not nullable for class AuditLogResponse.");

            if (userName.IsSet && userName.Value == null)
                throw new ArgumentNullException(nameof(userName), "Property is not nullable for class AuditLogResponse.");

            if (role.IsSet && role.Value == null)
                throw new ArgumentNullException(nameof(role), "Property is not nullable for class AuditLogResponse.");

            if (timestamp.IsSet && timestamp.Value == null)
                throw new ArgumentNullException(nameof(timestamp), "Property is not nullable for class AuditLogResponse.");

            return new AuditLogResponse(entryType, userName, role, timestamp, elementName, phase, stage);
        }

        /// <summary>
        /// Serializes a <see cref="AuditLogResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="auditLogResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AuditLogResponse auditLogResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, auditLogResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AuditLogResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="auditLogResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AuditLogResponse auditLogResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (auditLogResponse.EntryTypeOption.IsSet && auditLogResponse.EntryType == null)
                throw new ArgumentNullException(nameof(auditLogResponse.EntryType), "Property is required for class AuditLogResponse.");

            if (auditLogResponse.UserNameOption.IsSet && auditLogResponse.UserName == null)
                throw new ArgumentNullException(nameof(auditLogResponse.UserName), "Property is required for class AuditLogResponse.");

            if (auditLogResponse.RoleOption.IsSet && auditLogResponse.Role == null)
                throw new ArgumentNullException(nameof(auditLogResponse.Role), "Property is required for class AuditLogResponse.");

            if (auditLogResponse.TimestampOption.IsSet && auditLogResponse.Timestamp == null)
                throw new ArgumentNullException(nameof(auditLogResponse.Timestamp), "Property is required for class AuditLogResponse.");

            if (auditLogResponse.EntryTypeOption.IsSet)
                writer.WriteString("entryType", auditLogResponse.EntryType);

            if (auditLogResponse.UserNameOption.IsSet)
                writer.WriteString("userName", auditLogResponse.UserName);

            if (auditLogResponse.RoleOption.IsSet)
                writer.WriteString("role", auditLogResponse.Role);

            if (auditLogResponse.TimestampOption.IsSet)
                writer.WriteString("timestamp", auditLogResponse.Timestamp);

            if (auditLogResponse.ElementNameOption.IsSet)
                if (auditLogResponse.ElementNameOption.Value != null)
                    writer.WriteString("elementName", auditLogResponse.ElementName);
                else
                    writer.WriteNull("elementName");

            if (auditLogResponse.PhaseOption.IsSet)
                if (auditLogResponse.PhaseOption.Value != null)
                    writer.WriteString("phase", auditLogResponse.Phase);
                else
                    writer.WriteNull("phase");

            if (auditLogResponse.StageOption.IsSet)
                if (auditLogResponse.StageOption.Value != null)
                    writer.WriteString("stage", auditLogResponse.Stage);
                else
                    writer.WriteNull("stage");
        }
    }
}
