// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// Defines ConnectionType
    /// </summary>
    public enum ConnectionType
    {
        /// <summary>
        /// Enum CommunalBuildings for value: CommunalBuildings
        /// </summary>
        CommunalBuildings = 1,

        /// <summary>
        /// Enum IndividualHomes for value: IndividualHomes
        /// </summary>
        IndividualHomes = 2,

        /// <summary>
        /// Enum CommercialConnection for value: CommercialConnection
        /// </summary>
        CommercialConnection = 3,

        /// <summary>
        /// Enum OtherDistrictNetwork for value: OtherDistrictNetwork
        /// </summary>
        OtherDistrictNetwork = 4
    }

    /// <summary>
    /// Converts <see cref="ConnectionType"/> to and from the JSON value
    /// </summary>
    public static class ConnectionTypeValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="ConnectionType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ConnectionType FromString(string value)
        {
            if (value.Equals("CommunalBuildings"))
                return ConnectionType.CommunalBuildings;

            if (value.Equals("IndividualHomes"))
                return ConnectionType.IndividualHomes;

            if (value.Equals("CommercialConnection"))
                return ConnectionType.CommercialConnection;

            if (value.Equals("OtherDistrictNetwork"))
                return ConnectionType.OtherDistrictNetwork;

            throw new NotImplementedException($"Could not convert value to type ConnectionType: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="ConnectionType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ConnectionType? FromStringOrDefault(string value)
        {
            if (value.Equals("CommunalBuildings"))
                return ConnectionType.CommunalBuildings;

            if (value.Equals("IndividualHomes"))
                return ConnectionType.IndividualHomes;

            if (value.Equals("CommercialConnection"))
                return ConnectionType.CommercialConnection;

            if (value.Equals("OtherDistrictNetwork"))
                return ConnectionType.OtherDistrictNetwork;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ConnectionType"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(ConnectionType value)
        {
            if (value == ConnectionType.CommunalBuildings)
                return "CommunalBuildings";

            if (value == ConnectionType.IndividualHomes)
                return "IndividualHomes";

            if (value == ConnectionType.CommercialConnection)
                return "CommercialConnection";

            if (value == ConnectionType.OtherDistrictNetwork)
                return "OtherDistrictNetwork";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ConnectionType"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class ConnectionTypeJsonConverter : JsonConverter<ConnectionType>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override ConnectionType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            ConnectionType? result = rawValue == null
                ? null
                : ConnectionTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the ConnectionType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="connectionType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, ConnectionType connectionType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(connectionType.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ConnectionType"/>
    /// </summary>
    public class ConnectionTypeNullableJsonConverter : JsonConverter<ConnectionType?>
    {
        /// <summary>
        /// Returns a ConnectionType from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override ConnectionType? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            ConnectionType? result = rawValue == null
                ? null
                : ConnectionTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="connectionType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, ConnectionType? connectionType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(connectionType?.ToString() ?? "null");
        }
    }
}
