// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// DistributionNetworksAndSubstations
    /// </summary>
    public partial class DistributionNetworksAndSubstations : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DistributionNetworksAndSubstations" /> class.
        /// </summary>
        /// <param name="isAnyDistrictSubstations">isAnyDistrictSubstations</param>
        /// <param name="numberOfSubstations">numberOfSubstations</param>
        /// <param name="numberOfDistributionNetworks">numberOfDistributionNetworks</param>
        [JsonConstructor]
        public DistributionNetworksAndSubstations(Option<bool?> isAnyDistrictSubstations = default, Option<int?> numberOfSubstations = default, Option<int?> numberOfDistributionNetworks = default)
        {
            IsAnyDistrictSubstationsOption = isAnyDistrictSubstations;
            NumberOfSubstationsOption = numberOfSubstations;
            NumberOfDistributionNetworksOption = numberOfDistributionNetworks;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of IsAnyDistrictSubstations
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsAnyDistrictSubstationsOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsAnyDistrictSubstations
        /// </summary>
        [JsonPropertyName("isAnyDistrictSubstations")]
        public bool? IsAnyDistrictSubstations { get { return this.IsAnyDistrictSubstationsOption; } set { this.IsAnyDistrictSubstationsOption = new(value); } }

        /// <summary>
        /// Used to track the state of NumberOfSubstations
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> NumberOfSubstationsOption { get; private set; }

        /// <summary>
        /// Gets or Sets NumberOfSubstations
        /// </summary>
        [JsonPropertyName("numberOfSubstations")]
        public int? NumberOfSubstations { get { return this.NumberOfSubstationsOption; } set { this.NumberOfSubstationsOption = new(value); } }

        /// <summary>
        /// Used to track the state of NumberOfDistributionNetworks
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> NumberOfDistributionNetworksOption { get; private set; }

        /// <summary>
        /// Gets or Sets NumberOfDistributionNetworks
        /// </summary>
        [JsonPropertyName("numberOfDistributionNetworks")]
        public int? NumberOfDistributionNetworks { get { return this.NumberOfDistributionNetworksOption; } set { this.NumberOfDistributionNetworksOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DistributionNetworksAndSubstations {\n");
            sb.Append("  IsAnyDistrictSubstations: ").Append(IsAnyDistrictSubstations).Append("\n");
            sb.Append("  NumberOfSubstations: ").Append(NumberOfSubstations).Append("\n");
            sb.Append("  NumberOfDistributionNetworks: ").Append(NumberOfDistributionNetworks).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DistributionNetworksAndSubstations" />
    /// </summary>
    public class DistributionNetworksAndSubstationsJsonConverter : JsonConverter<DistributionNetworksAndSubstations>
    {
        /// <summary>
        /// Deserializes json to <see cref="DistributionNetworksAndSubstations" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DistributionNetworksAndSubstations Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> isAnyDistrictSubstations = default;
            Option<int?> numberOfSubstations = default;
            Option<int?> numberOfDistributionNetworks = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "isAnyDistrictSubstations":
                            isAnyDistrictSubstations = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "numberOfSubstations":
                            numberOfSubstations = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "numberOfDistributionNetworks":
                            numberOfDistributionNetworks = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new DistributionNetworksAndSubstations(isAnyDistrictSubstations, numberOfSubstations, numberOfDistributionNetworks);
        }

        /// <summary>
        /// Serializes a <see cref="DistributionNetworksAndSubstations" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="distributionNetworksAndSubstations"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DistributionNetworksAndSubstations distributionNetworksAndSubstations, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, distributionNetworksAndSubstations, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DistributionNetworksAndSubstations" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="distributionNetworksAndSubstations"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DistributionNetworksAndSubstations distributionNetworksAndSubstations, JsonSerializerOptions jsonSerializerOptions)
        {
            if (distributionNetworksAndSubstations.IsAnyDistrictSubstationsOption.IsSet)
                if (distributionNetworksAndSubstations.IsAnyDistrictSubstationsOption.Value != null)
                    writer.WriteBoolean("isAnyDistrictSubstations", distributionNetworksAndSubstations.IsAnyDistrictSubstationsOption.Value!.Value);
                else
                    writer.WriteNull("isAnyDistrictSubstations");

            if (distributionNetworksAndSubstations.NumberOfSubstationsOption.IsSet)
                if (distributionNetworksAndSubstations.NumberOfSubstationsOption.Value != null)
                    writer.WriteNumber("numberOfSubstations", distributionNetworksAndSubstations.NumberOfSubstationsOption.Value!.Value);
                else
                    writer.WriteNull("numberOfSubstations");

            if (distributionNetworksAndSubstations.NumberOfDistributionNetworksOption.IsSet)
                if (distributionNetworksAndSubstations.NumberOfDistributionNetworksOption.Value != null)
                    writer.WriteNumber("numberOfDistributionNetworks", distributionNetworksAndSubstations.NumberOfDistributionNetworksOption.Value!.Value);
                else
                    writer.WriteNull("numberOfDistributionNetworks");
        }
    }
}
