// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// Defines DocumentType
    /// </summary>
    public enum DocumentType
    {
        /// <summary>
        /// Enum Assessment for value: Assessment
        /// </summary>
        Assessment = 1,

        /// <summary>
        /// Enum Assessor for value: Assessor
        /// </summary>
        Assessor = 2,

        /// <summary>
        /// Enum Certifier for value: Certifier
        /// </summary>
        Certifier = 3,

        /// <summary>
        /// Enum MeteringAndMonitoringStrategy for value: MeteringAndMonitoringStrategy
        /// </summary>
        MeteringAndMonitoringStrategy = 4,

        /// <summary>
        /// Enum AssessmentPlan for value: AssessmentPlan
        /// </summary>
        AssessmentPlan = 5,

        /// <summary>
        /// Enum DesignConstructionLog for value: DesignConstructionLog
        /// </summary>
        DesignConstructionLog = 6,

        /// <summary>
        /// Enum Soa for value: Soa
        /// </summary>
        Soa = 7
    }

    /// <summary>
    /// Converts <see cref="DocumentType"/> to and from the JSON value
    /// </summary>
    public static class DocumentTypeValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="DocumentType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static DocumentType FromString(string value)
        {
            if (value.Equals("Assessment"))
                return DocumentType.Assessment;

            if (value.Equals("Assessor"))
                return DocumentType.Assessor;

            if (value.Equals("Certifier"))
                return DocumentType.Certifier;

            if (value.Equals("MeteringAndMonitoringStrategy"))
                return DocumentType.MeteringAndMonitoringStrategy;

            if (value.Equals("AssessmentPlan"))
                return DocumentType.AssessmentPlan;

            if (value.Equals("DesignConstructionLog"))
                return DocumentType.DesignConstructionLog;

            if (value.Equals("Soa"))
                return DocumentType.Soa;

            throw new NotImplementedException($"Could not convert value to type DocumentType: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="DocumentType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static DocumentType? FromStringOrDefault(string value)
        {
            if (value.Equals("Assessment"))
                return DocumentType.Assessment;

            if (value.Equals("Assessor"))
                return DocumentType.Assessor;

            if (value.Equals("Certifier"))
                return DocumentType.Certifier;

            if (value.Equals("MeteringAndMonitoringStrategy"))
                return DocumentType.MeteringAndMonitoringStrategy;

            if (value.Equals("AssessmentPlan"))
                return DocumentType.AssessmentPlan;

            if (value.Equals("DesignConstructionLog"))
                return DocumentType.DesignConstructionLog;

            if (value.Equals("Soa"))
                return DocumentType.Soa;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="DocumentType"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(DocumentType value)
        {
            if (value == DocumentType.Assessment)
                return "Assessment";

            if (value == DocumentType.Assessor)
                return "Assessor";

            if (value == DocumentType.Certifier)
                return "Certifier";

            if (value == DocumentType.MeteringAndMonitoringStrategy)
                return "MeteringAndMonitoringStrategy";

            if (value == DocumentType.AssessmentPlan)
                return "AssessmentPlan";

            if (value == DocumentType.DesignConstructionLog)
                return "DesignConstructionLog";

            if (value == DocumentType.Soa)
                return "Soa";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DocumentType"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class DocumentTypeJsonConverter : JsonConverter<DocumentType>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override DocumentType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            DocumentType? result = rawValue == null
                ? null
                : DocumentTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DocumentType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="documentType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, DocumentType documentType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(DocumentTypeValueConverter.ToJsonValue(documentType).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DocumentType"/>
    /// </summary>
    public class DocumentTypeNullableJsonConverter : JsonConverter<DocumentType?>
    {
        /// <summary>
        /// Returns a DocumentType from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override DocumentType? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            DocumentType? result = rawValue == null
                ? null
                : DocumentTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DocumentType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="documentType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, DocumentType? documentType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(documentType.HasValue ? DocumentTypeValueConverter.ToJsonValue(documentType.Value).ToString() : "null");
        }
    }
}
