// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// ElementSoaUploadDocumentRequest
    /// </summary>
    public partial class ElementSoaUploadDocumentRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ElementSoaUploadDocumentRequest" /> class.
        /// </summary>
        /// <param name="hnId">hnId</param>
        /// <param name="uploadedBy">uploadedBy</param>
        /// <param name="fileName">fileName</param>
        /// <param name="s3Key">s3Key</param>
        /// <param name="documentType">documentType</param>
        /// <param name="stage">stage</param>
        /// <param name="elementId">elementId</param>
        /// <param name="elementSoaStatus">elementSoaStatus</param>
        [JsonConstructor]
        public ElementSoaUploadDocumentRequest(string hnId, string uploadedBy, string fileName, string s3Key, DocumentType documentType, Option<SoaStage?> stage = default, Option<string?> elementId = default, Option<NetworkDetailsStatus?> elementSoaStatus = default)
        {
            HnId = hnId;
            UploadedBy = uploadedBy;
            FileName = fileName;
            S3Key = s3Key;
            DocumentType = documentType;
            StageOption = stage;
            ElementIdOption = elementId;
            ElementSoaStatusOption = elementSoaStatus;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets DocumentType
        /// </summary>
        [JsonPropertyName("documentType")]
        public DocumentType DocumentType { get; set; }

        /// <summary>
        /// Used to track the state of Stage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SoaStage?> StageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Stage
        /// </summary>
        [JsonPropertyName("stage")]
        public SoaStage? Stage { get { return this.StageOption; } set { this.StageOption = new(value); } }

        /// <summary>
        /// Used to track the state of ElementSoaStatus
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<NetworkDetailsStatus?> ElementSoaStatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets ElementSoaStatus
        /// </summary>
        [JsonPropertyName("elementSoaStatus")]
        public NetworkDetailsStatus? ElementSoaStatus { get { return this.ElementSoaStatusOption; } set { this.ElementSoaStatusOption = new(value); } }

        /// <summary>
        /// Gets or Sets HnId
        /// </summary>
        [JsonPropertyName("hnId")]
        public string HnId { get; set; }

        /// <summary>
        /// Gets or Sets UploadedBy
        /// </summary>
        [JsonPropertyName("uploadedBy")]
        public string UploadedBy { get; set; }

        /// <summary>
        /// Gets or Sets FileName
        /// </summary>
        [JsonPropertyName("fileName")]
        public string FileName { get; set; }

        /// <summary>
        /// Gets or Sets S3Key
        /// </summary>
        [JsonPropertyName("s3Key")]
        public string S3Key { get; set; }

        /// <summary>
        /// Used to track the state of ElementId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ElementIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ElementId
        /// </summary>
        [JsonPropertyName("elementId")]
        public string? ElementId { get { return this.ElementIdOption; } set { this.ElementIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ElementSoaUploadDocumentRequest {\n");
            sb.Append("  HnId: ").Append(HnId).Append("\n");
            sb.Append("  UploadedBy: ").Append(UploadedBy).Append("\n");
            sb.Append("  FileName: ").Append(FileName).Append("\n");
            sb.Append("  S3Key: ").Append(S3Key).Append("\n");
            sb.Append("  DocumentType: ").Append(DocumentType).Append("\n");
            sb.Append("  Stage: ").Append(Stage).Append("\n");
            sb.Append("  ElementId: ").Append(ElementId).Append("\n");
            sb.Append("  ElementSoaStatus: ").Append(ElementSoaStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ElementSoaUploadDocumentRequest" />
    /// </summary>
    public class ElementSoaUploadDocumentRequestJsonConverter : JsonConverter<ElementSoaUploadDocumentRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="ElementSoaUploadDocumentRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ElementSoaUploadDocumentRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> hnId = default;
            Option<string?> uploadedBy = default;
            Option<string?> fileName = default;
            Option<string?> s3Key = default;
            Option<DocumentType?> documentType = default;
            Option<SoaStage?> stage = default;
            Option<string?> elementId = default;
            Option<NetworkDetailsStatus?> elementSoaStatus = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "hnId":
                            hnId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "uploadedBy":
                            uploadedBy = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "fileName":
                            fileName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "s3Key":
                            s3Key = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "documentType":
                            string? documentTypeRawValue = utf8JsonReader.GetString();
                            if (documentTypeRawValue != null)
                                documentType = new Option<DocumentType?>(DocumentTypeValueConverter.FromStringOrDefault(documentTypeRawValue));
                            break;
                        case "stage":
                            string? stageRawValue = utf8JsonReader.GetString();
                            if (stageRawValue != null)
                                stage = new Option<SoaStage?>(SoaStageValueConverter.FromStringOrDefault(stageRawValue));
                            break;
                        case "elementId":
                            elementId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "elementSoaStatus":
                            string? elementSoaStatusRawValue = utf8JsonReader.GetString();
                            if (elementSoaStatusRawValue != null)
                                elementSoaStatus = new Option<NetworkDetailsStatus?>(NetworkDetailsStatusValueConverter.FromStringOrDefault(elementSoaStatusRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!hnId.IsSet)
                throw new ArgumentException("Property is required for class ElementSoaUploadDocumentRequest.", nameof(hnId));

            if (!uploadedBy.IsSet)
                throw new ArgumentException("Property is required for class ElementSoaUploadDocumentRequest.", nameof(uploadedBy));

            if (!fileName.IsSet)
                throw new ArgumentException("Property is required for class ElementSoaUploadDocumentRequest.", nameof(fileName));

            if (!s3Key.IsSet)
                throw new ArgumentException("Property is required for class ElementSoaUploadDocumentRequest.", nameof(s3Key));

            if (!documentType.IsSet)
                throw new ArgumentException("Property is required for class ElementSoaUploadDocumentRequest.", nameof(documentType));

            if (hnId.IsSet && hnId.Value == null)
                throw new ArgumentNullException(nameof(hnId), "Property is not nullable for class ElementSoaUploadDocumentRequest.");

            if (uploadedBy.IsSet && uploadedBy.Value == null)
                throw new ArgumentNullException(nameof(uploadedBy), "Property is not nullable for class ElementSoaUploadDocumentRequest.");

            if (fileName.IsSet && fileName.Value == null)
                throw new ArgumentNullException(nameof(fileName), "Property is not nullable for class ElementSoaUploadDocumentRequest.");

            if (s3Key.IsSet && s3Key.Value == null)
                throw new ArgumentNullException(nameof(s3Key), "Property is not nullable for class ElementSoaUploadDocumentRequest.");

            if (documentType.IsSet && documentType.Value == null)
                throw new ArgumentNullException(nameof(documentType), "Property is not nullable for class ElementSoaUploadDocumentRequest.");

            if (stage.IsSet && stage.Value == null)
                throw new ArgumentNullException(nameof(stage), "Property is not nullable for class ElementSoaUploadDocumentRequest.");

            if (elementSoaStatus.IsSet && elementSoaStatus.Value == null)
                throw new ArgumentNullException(nameof(elementSoaStatus), "Property is not nullable for class ElementSoaUploadDocumentRequest.");

            return new ElementSoaUploadDocumentRequest(hnId.Value!, uploadedBy.Value!, fileName.Value!, s3Key.Value!, documentType.Value!.Value!, stage, elementId, elementSoaStatus);
        }

        /// <summary>
        /// Serializes a <see cref="ElementSoaUploadDocumentRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="elementSoaUploadDocumentRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ElementSoaUploadDocumentRequest elementSoaUploadDocumentRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, elementSoaUploadDocumentRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ElementSoaUploadDocumentRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="elementSoaUploadDocumentRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ElementSoaUploadDocumentRequest elementSoaUploadDocumentRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (elementSoaUploadDocumentRequest.HnId == null)
                throw new ArgumentNullException(nameof(elementSoaUploadDocumentRequest.HnId), "Property is required for class ElementSoaUploadDocumentRequest.");

            if (elementSoaUploadDocumentRequest.UploadedBy == null)
                throw new ArgumentNullException(nameof(elementSoaUploadDocumentRequest.UploadedBy), "Property is required for class ElementSoaUploadDocumentRequest.");

            if (elementSoaUploadDocumentRequest.FileName == null)
                throw new ArgumentNullException(nameof(elementSoaUploadDocumentRequest.FileName), "Property is required for class ElementSoaUploadDocumentRequest.");

            if (elementSoaUploadDocumentRequest.S3Key == null)
                throw new ArgumentNullException(nameof(elementSoaUploadDocumentRequest.S3Key), "Property is required for class ElementSoaUploadDocumentRequest.");

            writer.WriteString("hnId", elementSoaUploadDocumentRequest.HnId);

            writer.WriteString("uploadedBy", elementSoaUploadDocumentRequest.UploadedBy);

            writer.WriteString("fileName", elementSoaUploadDocumentRequest.FileName);

            writer.WriteString("s3Key", elementSoaUploadDocumentRequest.S3Key);

            var documentTypeRawValue = DocumentTypeValueConverter.ToJsonValue(elementSoaUploadDocumentRequest.DocumentType);
            writer.WriteString("documentType", documentTypeRawValue);

            if (elementSoaUploadDocumentRequest.StageOption.IsSet)
            {
                var stageRawValue = SoaStageValueConverter.ToJsonValue(elementSoaUploadDocumentRequest.Stage!.Value);
                writer.WriteString("stage", stageRawValue);
            }
            if (elementSoaUploadDocumentRequest.ElementIdOption.IsSet)
                if (elementSoaUploadDocumentRequest.ElementIdOption.Value != null)
                    writer.WriteString("elementId", elementSoaUploadDocumentRequest.ElementId);
                else
                    writer.WriteNull("elementId");

            if (elementSoaUploadDocumentRequest.ElementSoaStatusOption.IsSet)
            {
                var elementSoaStatusRawValue = NetworkDetailsStatusValueConverter.ToJsonValue(elementSoaUploadDocumentRequest.ElementSoaStatus!.Value);
                writer.WriteString("elementSoaStatus", elementSoaStatusRawValue);
            }
        }
    }
}
