// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// Defines ElementTypeInShort
    /// </summary>
    public enum ElementTypeInShort
    {
        /// <summary>
        /// Enum EC for value: EC
        /// </summary>
        EC = 1,

        /// <summary>
        /// Enum SS for value: SS
        /// </summary>
        SS = 2,

        /// <summary>
        /// Enum DDN for value: DDN
        /// </summary>
        DDN = 3,

        /// <summary>
        /// Enum CDN for value: CDN
        /// </summary>
        CDN = 4,

        /// <summary>
        /// Enum CC for value: CC
        /// </summary>
        CC = 5
    }

    /// <summary>
    /// Converts <see cref="ElementTypeInShort"/> to and from the JSON value
    /// </summary>
    public static class ElementTypeInShortValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="ElementTypeInShort"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ElementTypeInShort FromString(string value)
        {
            if (value.Equals("EC"))
                return ElementTypeInShort.EC;

            if (value.Equals("SS"))
                return ElementTypeInShort.SS;

            if (value.Equals("DDN"))
                return ElementTypeInShort.DDN;

            if (value.Equals("CDN"))
                return ElementTypeInShort.CDN;

            if (value.Equals("CC"))
                return ElementTypeInShort.CC;

            throw new NotImplementedException($"Could not convert value to type ElementTypeInShort: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="ElementTypeInShort"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ElementTypeInShort? FromStringOrDefault(string value)
        {
            if (value.Equals("EC"))
                return ElementTypeInShort.EC;

            if (value.Equals("SS"))
                return ElementTypeInShort.SS;

            if (value.Equals("DDN"))
                return ElementTypeInShort.DDN;

            if (value.Equals("CDN"))
                return ElementTypeInShort.CDN;

            if (value.Equals("CC"))
                return ElementTypeInShort.CC;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ElementTypeInShort"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(ElementTypeInShort value)
        {
            if (value == ElementTypeInShort.EC)
                return "EC";

            if (value == ElementTypeInShort.SS)
                return "SS";

            if (value == ElementTypeInShort.DDN)
                return "DDN";

            if (value == ElementTypeInShort.CDN)
                return "CDN";

            if (value == ElementTypeInShort.CC)
                return "CC";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ElementTypeInShort"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class ElementTypeInShortJsonConverter : JsonConverter<ElementTypeInShort>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override ElementTypeInShort Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            ElementTypeInShort? result = rawValue == null
                ? null
                : ElementTypeInShortValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the ElementTypeInShort to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="elementTypeInShort"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, ElementTypeInShort elementTypeInShort, JsonSerializerOptions options)
        {
            writer.WriteStringValue(ElementTypeInShortValueConverter.ToJsonValue(elementTypeInShort).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ElementTypeInShort"/>
    /// </summary>
    public class ElementTypeInShortNullableJsonConverter : JsonConverter<ElementTypeInShort?>
    {
        /// <summary>
        /// Returns a ElementTypeInShort from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override ElementTypeInShort? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            ElementTypeInShort? result = rawValue == null
                ? null
                : ElementTypeInShortValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the ElementTypeInShort to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="elementTypeInShort"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, ElementTypeInShort? elementTypeInShort, JsonSerializerOptions options)
        {
            writer.WriteStringValue(elementTypeInShort.HasValue ? ElementTypeInShortValueConverter.ToJsonValue(elementTypeInShort.Value).ToString() : "null");
        }
    }
}
