// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// ElementSoaAssignAssessorRequest
    /// </summary>
    public partial class ElementSoaAssignAssessorRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ElementSoaAssignAssessorRequest" /> class.
        /// </summary>
        /// <param name="elementsAndAssessments">elementsAndAssessments</param>
        /// <param name="assessorEmail">assessorEmail</param>
        /// <param name="assessorFirstName">assessorFirstName</param>
        /// <param name="assessorLastName">assessorLastName</param>
        /// <param name="soaStage">soaStage</param>
        /// <param name="hnId">hnId</param>
        /// <param name="updatedBy">updatedBy</param>
        [JsonConstructor]
        public ElementSoaAssignAssessorRequest(Option<List<ElementAndAssessment>?> elementsAndAssessments = default, Option<string?> assessorEmail = default, Option<string?> assessorFirstName = default, Option<string?> assessorLastName = default, Option<SoaStage?> soaStage = default, Option<string?> hnId = default, Option<string?> updatedBy = default)
        {
            ElementsAndAssessmentsOption = elementsAndAssessments;
            AssessorEmailOption = assessorEmail;
            AssessorFirstNameOption = assessorFirstName;
            AssessorLastNameOption = assessorLastName;
            SoaStageOption = soaStage;
            HnIdOption = hnId;
            UpdatedByOption = updatedBy;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of SoaStage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SoaStage?> SoaStageOption { get; private set; }

        /// <summary>
        /// Gets or Sets SoaStage
        /// </summary>
        [JsonPropertyName("soaStage")]
        public SoaStage? SoaStage { get { return this.SoaStageOption; } set { this.SoaStageOption = new(value); } }

        /// <summary>
        /// Used to track the state of ElementsAndAssessments
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ElementAndAssessment>?> ElementsAndAssessmentsOption { get; private set; }

        /// <summary>
        /// Gets or Sets ElementsAndAssessments
        /// </summary>
        [JsonPropertyName("elementsAndAssessments")]
        public List<ElementAndAssessment>? ElementsAndAssessments { get { return this.ElementsAndAssessmentsOption; } set { this.ElementsAndAssessmentsOption = new(value); } }

        /// <summary>
        /// Used to track the state of AssessorEmail
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AssessorEmailOption { get; private set; }

        /// <summary>
        /// Gets or Sets AssessorEmail
        /// </summary>
        [JsonPropertyName("assessorEmail")]
        public string? AssessorEmail { get { return this.AssessorEmailOption; } set { this.AssessorEmailOption = new(value); } }

        /// <summary>
        /// Used to track the state of AssessorFirstName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AssessorFirstNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets AssessorFirstName
        /// </summary>
        [JsonPropertyName("assessorFirstName")]
        public string? AssessorFirstName { get { return this.AssessorFirstNameOption; } set { this.AssessorFirstNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of AssessorLastName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AssessorLastNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets AssessorLastName
        /// </summary>
        [JsonPropertyName("assessorLastName")]
        public string? AssessorLastName { get { return this.AssessorLastNameOption; } set { this.AssessorLastNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of HnId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> HnIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets HnId
        /// </summary>
        [JsonPropertyName("hnId")]
        public string? HnId { get { return this.HnIdOption; } set { this.HnIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of UpdatedBy
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UpdatedByOption { get; private set; }

        /// <summary>
        /// Gets or Sets UpdatedBy
        /// </summary>
        [JsonPropertyName("updatedBy")]
        public string? UpdatedBy { get { return this.UpdatedByOption; } set { this.UpdatedByOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ElementSoaAssignAssessorRequest {\n");
            sb.Append("  ElementsAndAssessments: ").Append(ElementsAndAssessments).Append("\n");
            sb.Append("  AssessorEmail: ").Append(AssessorEmail).Append("\n");
            sb.Append("  AssessorFirstName: ").Append(AssessorFirstName).Append("\n");
            sb.Append("  AssessorLastName: ").Append(AssessorLastName).Append("\n");
            sb.Append("  SoaStage: ").Append(SoaStage).Append("\n");
            sb.Append("  HnId: ").Append(HnId).Append("\n");
            sb.Append("  UpdatedBy: ").Append(UpdatedBy).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ElementSoaAssignAssessorRequest" />
    /// </summary>
    public class ElementSoaAssignAssessorRequestJsonConverter : JsonConverter<ElementSoaAssignAssessorRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="ElementSoaAssignAssessorRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ElementSoaAssignAssessorRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<ElementAndAssessment>?> elementsAndAssessments = default;
            Option<string?> assessorEmail = default;
            Option<string?> assessorFirstName = default;
            Option<string?> assessorLastName = default;
            Option<SoaStage?> soaStage = default;
            Option<string?> hnId = default;
            Option<string?> updatedBy = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "elementsAndAssessments":
                            elementsAndAssessments = new Option<List<ElementAndAssessment>?>(JsonSerializer.Deserialize<List<ElementAndAssessment>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "assessorEmail":
                            assessorEmail = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "assessorFirstName":
                            assessorFirstName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "assessorLastName":
                            assessorLastName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "soaStage":
                            string? soaStageRawValue = utf8JsonReader.GetString();
                            if (soaStageRawValue != null)
                                soaStage = new Option<SoaStage?>(SoaStageValueConverter.FromStringOrDefault(soaStageRawValue));
                            break;
                        case "hnId":
                            hnId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "updatedBy":
                            updatedBy = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (elementsAndAssessments.IsSet && elementsAndAssessments.Value == null)
                throw new ArgumentNullException(nameof(elementsAndAssessments), "Property is not nullable for class ElementSoaAssignAssessorRequest.");

            if (assessorEmail.IsSet && assessorEmail.Value == null)
                throw new ArgumentNullException(nameof(assessorEmail), "Property is not nullable for class ElementSoaAssignAssessorRequest.");

            if (assessorFirstName.IsSet && assessorFirstName.Value == null)
                throw new ArgumentNullException(nameof(assessorFirstName), "Property is not nullable for class ElementSoaAssignAssessorRequest.");

            if (assessorLastName.IsSet && assessorLastName.Value == null)
                throw new ArgumentNullException(nameof(assessorLastName), "Property is not nullable for class ElementSoaAssignAssessorRequest.");

            if (soaStage.IsSet && soaStage.Value == null)
                throw new ArgumentNullException(nameof(soaStage), "Property is not nullable for class ElementSoaAssignAssessorRequest.");

            if (hnId.IsSet && hnId.Value == null)
                throw new ArgumentNullException(nameof(hnId), "Property is not nullable for class ElementSoaAssignAssessorRequest.");

            if (updatedBy.IsSet && updatedBy.Value == null)
                throw new ArgumentNullException(nameof(updatedBy), "Property is not nullable for class ElementSoaAssignAssessorRequest.");

            return new ElementSoaAssignAssessorRequest(elementsAndAssessments, assessorEmail, assessorFirstName, assessorLastName, soaStage, hnId, updatedBy);
        }

        /// <summary>
        /// Serializes a <see cref="ElementSoaAssignAssessorRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="elementSoaAssignAssessorRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ElementSoaAssignAssessorRequest elementSoaAssignAssessorRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, elementSoaAssignAssessorRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ElementSoaAssignAssessorRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="elementSoaAssignAssessorRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ElementSoaAssignAssessorRequest elementSoaAssignAssessorRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (elementSoaAssignAssessorRequest.ElementsAndAssessmentsOption.IsSet && elementSoaAssignAssessorRequest.ElementsAndAssessments == null)
                throw new ArgumentNullException(nameof(elementSoaAssignAssessorRequest.ElementsAndAssessments), "Property is required for class ElementSoaAssignAssessorRequest.");

            if (elementSoaAssignAssessorRequest.AssessorEmailOption.IsSet && elementSoaAssignAssessorRequest.AssessorEmail == null)
                throw new ArgumentNullException(nameof(elementSoaAssignAssessorRequest.AssessorEmail), "Property is required for class ElementSoaAssignAssessorRequest.");

            if (elementSoaAssignAssessorRequest.AssessorFirstNameOption.IsSet && elementSoaAssignAssessorRequest.AssessorFirstName == null)
                throw new ArgumentNullException(nameof(elementSoaAssignAssessorRequest.AssessorFirstName), "Property is required for class ElementSoaAssignAssessorRequest.");

            if (elementSoaAssignAssessorRequest.AssessorLastNameOption.IsSet && elementSoaAssignAssessorRequest.AssessorLastName == null)
                throw new ArgumentNullException(nameof(elementSoaAssignAssessorRequest.AssessorLastName), "Property is required for class ElementSoaAssignAssessorRequest.");

            if (elementSoaAssignAssessorRequest.HnIdOption.IsSet && elementSoaAssignAssessorRequest.HnId == null)
                throw new ArgumentNullException(nameof(elementSoaAssignAssessorRequest.HnId), "Property is required for class ElementSoaAssignAssessorRequest.");

            if (elementSoaAssignAssessorRequest.UpdatedByOption.IsSet && elementSoaAssignAssessorRequest.UpdatedBy == null)
                throw new ArgumentNullException(nameof(elementSoaAssignAssessorRequest.UpdatedBy), "Property is required for class ElementSoaAssignAssessorRequest.");

            if (elementSoaAssignAssessorRequest.ElementsAndAssessmentsOption.IsSet)
            {
                writer.WritePropertyName("elementsAndAssessments");
                JsonSerializer.Serialize(writer, elementSoaAssignAssessorRequest.ElementsAndAssessments, jsonSerializerOptions);
            }
            if (elementSoaAssignAssessorRequest.AssessorEmailOption.IsSet)
                writer.WriteString("assessorEmail", elementSoaAssignAssessorRequest.AssessorEmail);

            if (elementSoaAssignAssessorRequest.AssessorFirstNameOption.IsSet)
                writer.WriteString("assessorFirstName", elementSoaAssignAssessorRequest.AssessorFirstName);

            if (elementSoaAssignAssessorRequest.AssessorLastNameOption.IsSet)
                writer.WriteString("assessorLastName", elementSoaAssignAssessorRequest.AssessorLastName);

            if (elementSoaAssignAssessorRequest.SoaStageOption.IsSet)
            {
                var soaStageRawValue = SoaStageValueConverter.ToJsonValue(elementSoaAssignAssessorRequest.SoaStage!.Value);
                writer.WriteString("soaStage", soaStageRawValue);
            }
            if (elementSoaAssignAssessorRequest.HnIdOption.IsSet)
                writer.WriteString("hnId", elementSoaAssignAssessorRequest.HnId);

            if (elementSoaAssignAssessorRequest.UpdatedByOption.IsSet)
                writer.WriteString("updatedBy", elementSoaAssignAssessorRequest.UpdatedBy);
        }
    }
}
