// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// ExistingNetworkRequest
    /// </summary>
    public partial class ExistingNetworkRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExistingNetworkRequest" /> class.
        /// </summary>
        /// <param name="userId">userId</param>
        /// <param name="sortBy">sortBy</param>
        /// <param name="sortDirection">sortDirection</param>
        /// <param name="page">page</param>
        /// <param name="pageSize">pageSize</param>
        [JsonConstructor]
        public ExistingNetworkRequest(Option<string?> userId = default, Option<string?> sortBy = default, Option<string?> sortDirection = default, Option<int?> page = default, Option<int?> pageSize = default)
        {
            UserIdOption = userId;
            SortByOption = sortBy;
            SortDirectionOption = sortDirection;
            PageOption = page;
            PageSizeOption = pageSize;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of UserId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UserIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [JsonPropertyName("userId")]
        public string? UserId { get { return this.UserIdOption; } set { this.UserIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SortBy
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SortByOption { get; private set; }

        /// <summary>
        /// Gets or Sets SortBy
        /// </summary>
        [JsonPropertyName("sortBy")]
        public string? SortBy { get { return this.SortByOption; } set { this.SortByOption = new(value); } }

        /// <summary>
        /// Used to track the state of SortDirection
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SortDirectionOption { get; private set; }

        /// <summary>
        /// Gets or Sets SortDirection
        /// </summary>
        [JsonPropertyName("sortDirection")]
        public string? SortDirection { get { return this.SortDirectionOption; } set { this.SortDirectionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Page
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Page
        /// </summary>
        [JsonPropertyName("page")]
        public int? Page { get { return this.PageOption; } set { this.PageOption = new(value); } }

        /// <summary>
        /// Used to track the state of PageSize
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PageSizeOption { get; private set; }

        /// <summary>
        /// Gets or Sets PageSize
        /// </summary>
        [JsonPropertyName("pageSize")]
        public int? PageSize { get { return this.PageSizeOption; } set { this.PageSizeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExistingNetworkRequest {\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  SortBy: ").Append(SortBy).Append("\n");
            sb.Append("  SortDirection: ").Append(SortDirection).Append("\n");
            sb.Append("  Page: ").Append(Page).Append("\n");
            sb.Append("  PageSize: ").Append(PageSize).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ExistingNetworkRequest" />
    /// </summary>
    public class ExistingNetworkRequestJsonConverter : JsonConverter<ExistingNetworkRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="ExistingNetworkRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ExistingNetworkRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> userId = default;
            Option<string?> sortBy = default;
            Option<string?> sortDirection = default;
            Option<int?> page = default;
            Option<int?> pageSize = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "userId":
                            userId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "sortBy":
                            sortBy = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "sortDirection":
                            sortDirection = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "page":
                            page = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "pageSize":
                            pageSize = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (page.IsSet && page.Value == null)
                throw new ArgumentNullException(nameof(page), "Property is not nullable for class ExistingNetworkRequest.");

            if (pageSize.IsSet && pageSize.Value == null)
                throw new ArgumentNullException(nameof(pageSize), "Property is not nullable for class ExistingNetworkRequest.");

            return new ExistingNetworkRequest(userId, sortBy, sortDirection, page, pageSize);
        }

        /// <summary>
        /// Serializes a <see cref="ExistingNetworkRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="existingNetworkRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ExistingNetworkRequest existingNetworkRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, existingNetworkRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ExistingNetworkRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="existingNetworkRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ExistingNetworkRequest existingNetworkRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (existingNetworkRequest.UserIdOption.IsSet)
                if (existingNetworkRequest.UserIdOption.Value != null)
                    writer.WriteString("userId", existingNetworkRequest.UserId);
                else
                    writer.WriteNull("userId");

            if (existingNetworkRequest.SortByOption.IsSet)
                if (existingNetworkRequest.SortByOption.Value != null)
                    writer.WriteString("sortBy", existingNetworkRequest.SortBy);
                else
                    writer.WriteNull("sortBy");

            if (existingNetworkRequest.SortDirectionOption.IsSet)
                if (existingNetworkRequest.SortDirectionOption.Value != null)
                    writer.WriteString("sortDirection", existingNetworkRequest.SortDirection);
                else
                    writer.WriteNull("sortDirection");

            if (existingNetworkRequest.PageOption.IsSet)
                writer.WriteNumber("page", existingNetworkRequest.PageOption.Value!.Value);

            if (existingNetworkRequest.PageSizeOption.IsSet)
                writer.WriteNumber("pageSize", existingNetworkRequest.PageSizeOption.Value!.Value);
        }
    }
}
