// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// HeatNetwork
    /// </summary>
    public partial class HeatNetwork : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HeatNetwork" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="hnId">hnId</param>
        /// <param name="location">location</param>
        /// <param name="name">name</param>
        /// <param name="pathway">pathway</param>
        /// <param name="soa">soa</param>
        /// <param name="createdBy">createdBy</param>
        /// <param name="createdAt">createdAt</param>
        [JsonConstructor]
        public HeatNetwork(Option<string?> id = default, Option<string?> hnId = default, Option<string?> location = default, Option<string?> name = default, Option<string?> pathway = default, Option<Soa?> soa = default, Option<string?> createdBy = default, Option<DateTimeOffset?> createdAt = default)
        {
            IdOption = id;
            HnIdOption = hnId;
            LocationOption = location;
            NameOption = name;
            PathwayOption = pathway;
            SoaOption = soa;
            CreatedByOption = createdBy;
            CreatedAtOption = createdAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of HnId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> HnIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets HnId
        /// </summary>
        [JsonPropertyName("hnId")]
        public string? HnId { get { return this.HnIdOption; } set { this.HnIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Location
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LocationOption { get; private set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [JsonPropertyName("location")]
        public string? Location { get { return this.LocationOption; } set { this.LocationOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Pathway
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PathwayOption { get; private set; }

        /// <summary>
        /// Gets or Sets Pathway
        /// </summary>
        [JsonPropertyName("pathway")]
        public string? Pathway { get { return this.PathwayOption; } set { this.PathwayOption = new(value); } }

        /// <summary>
        /// Used to track the state of Soa
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Soa?> SoaOption { get; private set; }

        /// <summary>
        /// Gets or Sets Soa
        /// </summary>
        [JsonPropertyName("soa")]
        public Soa? Soa { get { return this.SoaOption; } set { this.SoaOption = new(value); } }

        /// <summary>
        /// Used to track the state of CreatedBy
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CreatedByOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreatedBy
        /// </summary>
        [JsonPropertyName("createdBy")]
        public string? CreatedBy { get { return this.CreatedByOption; } set { this.CreatedByOption = new(value); } }

        /// <summary>
        /// Used to track the state of CreatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTimeOffset?> CreatedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("createdAt")]
        public DateTimeOffset? CreatedAt { get { return this.CreatedAtOption; } set { this.CreatedAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HeatNetwork {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  HnId: ").Append(HnId).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Pathway: ").Append(Pathway).Append("\n");
            sb.Append("  Soa: ").Append(Soa).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="HeatNetwork" />
    /// </summary>
    public class HeatNetworkJsonConverter : JsonConverter<HeatNetwork>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="HeatNetwork" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override HeatNetwork Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> hnId = default;
            Option<string?> location = default;
            Option<string?> name = default;
            Option<string?> pathway = default;
            Option<Soa?> soa = default;
            Option<string?> createdBy = default;
            Option<DateTimeOffset?> createdAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "hnId":
                            hnId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "location":
                            location = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "pathway":
                            pathway = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "soa":
                            soa = new Option<Soa?>(JsonSerializer.Deserialize<Soa>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "createdBy":
                            createdBy = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "createdAt":
                            createdAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (location.IsSet && location.Value == null)
                throw new ArgumentNullException(nameof(location), "Property is not nullable for class HeatNetwork.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class HeatNetwork.");

            if (pathway.IsSet && pathway.Value == null)
                throw new ArgumentNullException(nameof(pathway), "Property is not nullable for class HeatNetwork.");

            if (createdBy.IsSet && createdBy.Value == null)
                throw new ArgumentNullException(nameof(createdBy), "Property is not nullable for class HeatNetwork.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class HeatNetwork.");

            return new HeatNetwork(id, hnId, location, name, pathway, soa, createdBy, createdAt);
        }

        /// <summary>
        /// Serializes a <see cref="HeatNetwork" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="heatNetwork"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, HeatNetwork heatNetwork, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, heatNetwork, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="HeatNetwork" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="heatNetwork"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, HeatNetwork heatNetwork, JsonSerializerOptions jsonSerializerOptions)
        {
            if (heatNetwork.LocationOption.IsSet && heatNetwork.Location == null)
                throw new ArgumentNullException(nameof(heatNetwork.Location), "Property is required for class HeatNetwork.");

            if (heatNetwork.NameOption.IsSet && heatNetwork.Name == null)
                throw new ArgumentNullException(nameof(heatNetwork.Name), "Property is required for class HeatNetwork.");

            if (heatNetwork.PathwayOption.IsSet && heatNetwork.Pathway == null)
                throw new ArgumentNullException(nameof(heatNetwork.Pathway), "Property is required for class HeatNetwork.");

            if (heatNetwork.CreatedByOption.IsSet && heatNetwork.CreatedBy == null)
                throw new ArgumentNullException(nameof(heatNetwork.CreatedBy), "Property is required for class HeatNetwork.");

            if (heatNetwork.IdOption.IsSet)
                if (heatNetwork.IdOption.Value != null)
                    writer.WriteString("id", heatNetwork.Id);
                else
                    writer.WriteNull("id");

            if (heatNetwork.HnIdOption.IsSet)
                if (heatNetwork.HnIdOption.Value != null)
                    writer.WriteString("hnId", heatNetwork.HnId);
                else
                    writer.WriteNull("hnId");

            if (heatNetwork.LocationOption.IsSet)
                writer.WriteString("location", heatNetwork.Location);

            if (heatNetwork.NameOption.IsSet)
                writer.WriteString("name", heatNetwork.Name);

            if (heatNetwork.PathwayOption.IsSet)
                writer.WriteString("pathway", heatNetwork.Pathway);

            if (heatNetwork.SoaOption.IsSet)
                if (heatNetwork.SoaOption.Value != null)
                {
                    writer.WritePropertyName("soa");
                    JsonSerializer.Serialize(writer, heatNetwork.Soa, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("soa");
            if (heatNetwork.CreatedByOption.IsSet)
                writer.WriteString("createdBy", heatNetwork.CreatedBy);

            if (heatNetwork.CreatedAtOption.IsSet)
                writer.WriteString("createdAt", heatNetwork.CreatedAtOption.Value!.Value.ToString(CreatedAtFormat));
        }
    }
}
