// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// Defines HeatNetworkType
    /// </summary>
    public enum HeatNetworkType
    {
        /// <summary>
        /// Enum CommunalWithIntegralEC for value: CommunalWithIntegralEC
        /// </summary>
        CommunalWithIntegralEC = 1,

        /// <summary>
        /// Enum CommunalWithSeparateUpstreamHN for value: CommunalWithSeparateUpstreamHN
        /// </summary>
        CommunalWithSeparateUpstreamHN = 2,

        /// <summary>
        /// Enum DistrictWithOwnEC for value: DistrictWithOwnEC
        /// </summary>
        DistrictWithOwnEC = 3,

        /// <summary>
        /// Enum DistrictWithSeparateUpstreamHN for value: DistrictWithSeparateUpstreamHN
        /// </summary>
        DistrictWithSeparateUpstreamHN = 4
    }

    /// <summary>
    /// Converts <see cref="HeatNetworkType"/> to and from the JSON value
    /// </summary>
    public static class HeatNetworkTypeValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="HeatNetworkType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static HeatNetworkType FromString(string value)
        {
            if (value.Equals("CommunalWithIntegralEC"))
                return HeatNetworkType.CommunalWithIntegralEC;

            if (value.Equals("CommunalWithSeparateUpstreamHN"))
                return HeatNetworkType.CommunalWithSeparateUpstreamHN;

            if (value.Equals("DistrictWithOwnEC"))
                return HeatNetworkType.DistrictWithOwnEC;

            if (value.Equals("DistrictWithSeparateUpstreamHN"))
                return HeatNetworkType.DistrictWithSeparateUpstreamHN;

            throw new NotImplementedException($"Could not convert value to type HeatNetworkType: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="HeatNetworkType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static HeatNetworkType? FromStringOrDefault(string value)
        {
            if (value.Equals("CommunalWithIntegralEC"))
                return HeatNetworkType.CommunalWithIntegralEC;

            if (value.Equals("CommunalWithSeparateUpstreamHN"))
                return HeatNetworkType.CommunalWithSeparateUpstreamHN;

            if (value.Equals("DistrictWithOwnEC"))
                return HeatNetworkType.DistrictWithOwnEC;

            if (value.Equals("DistrictWithSeparateUpstreamHN"))
                return HeatNetworkType.DistrictWithSeparateUpstreamHN;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="HeatNetworkType"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(HeatNetworkType value)
        {
            if (value == HeatNetworkType.CommunalWithIntegralEC)
                return "CommunalWithIntegralEC";

            if (value == HeatNetworkType.CommunalWithSeparateUpstreamHN)
                return "CommunalWithSeparateUpstreamHN";

            if (value == HeatNetworkType.DistrictWithOwnEC)
                return "DistrictWithOwnEC";

            if (value == HeatNetworkType.DistrictWithSeparateUpstreamHN)
                return "DistrictWithSeparateUpstreamHN";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="HeatNetworkType"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class HeatNetworkTypeJsonConverter : JsonConverter<HeatNetworkType>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override HeatNetworkType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            HeatNetworkType? result = rawValue == null
                ? null
                : HeatNetworkTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the HeatNetworkType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="heatNetworkType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, HeatNetworkType heatNetworkType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(HeatNetworkTypeValueConverter.ToJsonValue(heatNetworkType).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="HeatNetworkType"/>
    /// </summary>
    public class HeatNetworkTypeNullableJsonConverter : JsonConverter<HeatNetworkType?>
    {
        /// <summary>
        /// Returns a HeatNetworkType from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override HeatNetworkType? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            HeatNetworkType? result = rawValue == null
                ? null
                : HeatNetworkTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the HeatNetworkType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="heatNetworkType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, HeatNetworkType? heatNetworkType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(heatNetworkType.HasValue ? HeatNetworkTypeValueConverter.ToJsonValue(heatNetworkType.Value).ToString() : "null");
        }
    }
}
