// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// JourneyDataResponse
    /// </summary>
    public partial class JourneyDataResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JourneyDataResponse" /> class.
        /// </summary>
        /// <param name="networkType">networkType</param>
        /// <param name="connectionTypes">connectionTypes</param>
        /// <param name="heatNetworkElements">heatNetworkElements</param>
        /// <param name="hasAssessorDeclaredImpartiality">hasAssessorDeclaredImpartiality</param>
        /// <param name="assessmentDocs">assessmentDocs</param>
        /// <param name="assessorDocs">assessorDocs</param>
        /// <param name="certifierDocs">certifierDocs</param>
        [JsonConstructor]
        public JourneyDataResponse(Option<NetworkTypeResponse?> networkType = default, Option<List<string>?> connectionTypes = default, Option<List<HeatNetworkElementResponse>?> heatNetworkElements = default, Option<bool?> hasAssessorDeclaredImpartiality = default, Option<List<UploadedAssessmentDocumentResponse>?> assessmentDocs = default, Option<List<UploadedAssessorDocumentResponse>?> assessorDocs = default, Option<List<UploadedCertifierDocumentResponse>?> certifierDocs = default)
        {
            NetworkTypeOption = networkType;
            ConnectionTypesOption = connectionTypes;
            HeatNetworkElementsOption = heatNetworkElements;
            HasAssessorDeclaredImpartialityOption = hasAssessorDeclaredImpartiality;
            AssessmentDocsOption = assessmentDocs;
            AssessorDocsOption = assessorDocs;
            CertifierDocsOption = certifierDocs;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of NetworkType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<NetworkTypeResponse?> NetworkTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets NetworkType
        /// </summary>
        [JsonPropertyName("networkType")]
        public NetworkTypeResponse? NetworkType { get { return this.NetworkTypeOption; } set { this.NetworkTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of ConnectionTypes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> ConnectionTypesOption { get; private set; }

        /// <summary>
        /// Gets or Sets ConnectionTypes
        /// </summary>
        [JsonPropertyName("connectionTypes")]
        public List<string>? ConnectionTypes { get { return this.ConnectionTypesOption; } set { this.ConnectionTypesOption = new(value); } }

        /// <summary>
        /// Used to track the state of HeatNetworkElements
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<HeatNetworkElementResponse>?> HeatNetworkElementsOption { get; private set; }

        /// <summary>
        /// Gets or Sets HeatNetworkElements
        /// </summary>
        [JsonPropertyName("heatNetworkElements")]
        public List<HeatNetworkElementResponse>? HeatNetworkElements { get { return this.HeatNetworkElementsOption; } set { this.HeatNetworkElementsOption = new(value); } }

        /// <summary>
        /// Used to track the state of HasAssessorDeclaredImpartiality
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> HasAssessorDeclaredImpartialityOption { get; private set; }

        /// <summary>
        /// Gets or Sets HasAssessorDeclaredImpartiality
        /// </summary>
        [JsonPropertyName("hasAssessorDeclaredImpartiality")]
        public bool? HasAssessorDeclaredImpartiality { get { return this.HasAssessorDeclaredImpartialityOption; } set { this.HasAssessorDeclaredImpartialityOption = new(value); } }

        /// <summary>
        /// Used to track the state of AssessmentDocs
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<UploadedAssessmentDocumentResponse>?> AssessmentDocsOption { get; private set; }

        /// <summary>
        /// Gets or Sets AssessmentDocs
        /// </summary>
        [JsonPropertyName("assessmentDocs")]
        public List<UploadedAssessmentDocumentResponse>? AssessmentDocs { get { return this.AssessmentDocsOption; } set { this.AssessmentDocsOption = new(value); } }

        /// <summary>
        /// Used to track the state of AssessorDocs
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<UploadedAssessorDocumentResponse>?> AssessorDocsOption { get; private set; }

        /// <summary>
        /// Gets or Sets AssessorDocs
        /// </summary>
        [JsonPropertyName("assessorDocs")]
        public List<UploadedAssessorDocumentResponse>? AssessorDocs { get { return this.AssessorDocsOption; } set { this.AssessorDocsOption = new(value); } }

        /// <summary>
        /// Used to track the state of CertifierDocs
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<UploadedCertifierDocumentResponse>?> CertifierDocsOption { get; private set; }

        /// <summary>
        /// Gets or Sets CertifierDocs
        /// </summary>
        [JsonPropertyName("certifierDocs")]
        public List<UploadedCertifierDocumentResponse>? CertifierDocs { get { return this.CertifierDocsOption; } set { this.CertifierDocsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JourneyDataResponse {\n");
            sb.Append("  NetworkType: ").Append(NetworkType).Append("\n");
            sb.Append("  ConnectionTypes: ").Append(ConnectionTypes).Append("\n");
            sb.Append("  HeatNetworkElements: ").Append(HeatNetworkElements).Append("\n");
            sb.Append("  HasAssessorDeclaredImpartiality: ").Append(HasAssessorDeclaredImpartiality).Append("\n");
            sb.Append("  AssessmentDocs: ").Append(AssessmentDocs).Append("\n");
            sb.Append("  AssessorDocs: ").Append(AssessorDocs).Append("\n");
            sb.Append("  CertifierDocs: ").Append(CertifierDocs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="JourneyDataResponse" />
    /// </summary>
    public class JourneyDataResponseJsonConverter : JsonConverter<JourneyDataResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="JourneyDataResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override JourneyDataResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<NetworkTypeResponse?> networkType = default;
            Option<List<string>?> connectionTypes = default;
            Option<List<HeatNetworkElementResponse>?> heatNetworkElements = default;
            Option<bool?> hasAssessorDeclaredImpartiality = default;
            Option<List<UploadedAssessmentDocumentResponse>?> assessmentDocs = default;
            Option<List<UploadedAssessorDocumentResponse>?> assessorDocs = default;
            Option<List<UploadedCertifierDocumentResponse>?> certifierDocs = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "networkType":
                            networkType = new Option<NetworkTypeResponse?>(JsonSerializer.Deserialize<NetworkTypeResponse>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "connectionTypes":
                            connectionTypes = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "heatNetworkElements":
                            heatNetworkElements = new Option<List<HeatNetworkElementResponse>?>(JsonSerializer.Deserialize<List<HeatNetworkElementResponse>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "hasAssessorDeclaredImpartiality":
                            hasAssessorDeclaredImpartiality = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "assessmentDocs":
                            assessmentDocs = new Option<List<UploadedAssessmentDocumentResponse>?>(JsonSerializer.Deserialize<List<UploadedAssessmentDocumentResponse>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "assessorDocs":
                            assessorDocs = new Option<List<UploadedAssessorDocumentResponse>?>(JsonSerializer.Deserialize<List<UploadedAssessorDocumentResponse>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "certifierDocs":
                            certifierDocs = new Option<List<UploadedCertifierDocumentResponse>?>(JsonSerializer.Deserialize<List<UploadedCertifierDocumentResponse>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (heatNetworkElements.IsSet && heatNetworkElements.Value == null)
                throw new ArgumentNullException(nameof(heatNetworkElements), "Property is not nullable for class JourneyDataResponse.");

            if (hasAssessorDeclaredImpartiality.IsSet && hasAssessorDeclaredImpartiality.Value == null)
                throw new ArgumentNullException(nameof(hasAssessorDeclaredImpartiality), "Property is not nullable for class JourneyDataResponse.");

            if (assessmentDocs.IsSet && assessmentDocs.Value == null)
                throw new ArgumentNullException(nameof(assessmentDocs), "Property is not nullable for class JourneyDataResponse.");

            if (assessorDocs.IsSet && assessorDocs.Value == null)
                throw new ArgumentNullException(nameof(assessorDocs), "Property is not nullable for class JourneyDataResponse.");

            if (certifierDocs.IsSet && certifierDocs.Value == null)
                throw new ArgumentNullException(nameof(certifierDocs), "Property is not nullable for class JourneyDataResponse.");

            return new JourneyDataResponse(networkType, connectionTypes, heatNetworkElements, hasAssessorDeclaredImpartiality, assessmentDocs, assessorDocs, certifierDocs);
        }

        /// <summary>
        /// Serializes a <see cref="JourneyDataResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="journeyDataResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, JourneyDataResponse journeyDataResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, journeyDataResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="JourneyDataResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="journeyDataResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, JourneyDataResponse journeyDataResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (journeyDataResponse.HeatNetworkElementsOption.IsSet && journeyDataResponse.HeatNetworkElements == null)
                throw new ArgumentNullException(nameof(journeyDataResponse.HeatNetworkElements), "Property is required for class JourneyDataResponse.");

            if (journeyDataResponse.AssessmentDocsOption.IsSet && journeyDataResponse.AssessmentDocs == null)
                throw new ArgumentNullException(nameof(journeyDataResponse.AssessmentDocs), "Property is required for class JourneyDataResponse.");

            if (journeyDataResponse.AssessorDocsOption.IsSet && journeyDataResponse.AssessorDocs == null)
                throw new ArgumentNullException(nameof(journeyDataResponse.AssessorDocs), "Property is required for class JourneyDataResponse.");

            if (journeyDataResponse.CertifierDocsOption.IsSet && journeyDataResponse.CertifierDocs == null)
                throw new ArgumentNullException(nameof(journeyDataResponse.CertifierDocs), "Property is required for class JourneyDataResponse.");

            if (journeyDataResponse.NetworkTypeOption.IsSet)
                if (journeyDataResponse.NetworkTypeOption.Value != null)
                {
                    writer.WritePropertyName("networkType");
                    JsonSerializer.Serialize(writer, journeyDataResponse.NetworkType, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("networkType");
            if (journeyDataResponse.ConnectionTypesOption.IsSet)
                if (journeyDataResponse.ConnectionTypesOption.Value != null)
                {
                    writer.WritePropertyName("connectionTypes");
                    JsonSerializer.Serialize(writer, journeyDataResponse.ConnectionTypes, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("connectionTypes");
            if (journeyDataResponse.HeatNetworkElementsOption.IsSet)
            {
                writer.WritePropertyName("heatNetworkElements");
                JsonSerializer.Serialize(writer, journeyDataResponse.HeatNetworkElements, jsonSerializerOptions);
            }
            if (journeyDataResponse.HasAssessorDeclaredImpartialityOption.IsSet)
                writer.WriteBoolean("hasAssessorDeclaredImpartiality", journeyDataResponse.HasAssessorDeclaredImpartialityOption.Value!.Value);

            if (journeyDataResponse.AssessmentDocsOption.IsSet)
            {
                writer.WritePropertyName("assessmentDocs");
                JsonSerializer.Serialize(writer, journeyDataResponse.AssessmentDocs, jsonSerializerOptions);
            }
            if (journeyDataResponse.AssessorDocsOption.IsSet)
            {
                writer.WritePropertyName("assessorDocs");
                JsonSerializer.Serialize(writer, journeyDataResponse.AssessorDocs, jsonSerializerOptions);
            }
            if (journeyDataResponse.CertifierDocsOption.IsSet)
            {
                writer.WritePropertyName("certifierDocs");
                JsonSerializer.Serialize(writer, journeyDataResponse.CertifierDocs, jsonSerializerOptions);
            }
        }
    }
}
