// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// KpiHistoryResponse
    /// </summary>
    public partial class KpiHistoryResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KpiHistoryResponse" /> class.
        /// </summary>
        /// <param name="timestamp">timestamp</param>
        /// <param name="sourceSystem">sourceSystem</param>
        /// <param name="kpiId">kpiId</param>
        /// <param name="elementId">elementId</param>
        /// <param name="isAggregated">isAggregated</param>
        /// <param name="oldValue">oldValue</param>
        /// <param name="newValue">newValue</param>
        /// <param name="oldStatus">oldStatus</param>
        /// <param name="newStatus">newStatus</param>
        /// <param name="isImputed">isImputed</param>
        [JsonConstructor]
        public KpiHistoryResponse(Option<DateTimeOffset?> timestamp = default, Option<string?> sourceSystem = default, Option<string?> kpiId = default, Option<string?> elementId = default, Option<bool?> isAggregated = default, Option<string?> oldValue = default, Option<string?> newValue = default, Option<string?> oldStatus = default, Option<string?> newStatus = default, Option<bool?> isImputed = default)
        {
            TimestampOption = timestamp;
            SourceSystemOption = sourceSystem;
            KpiIdOption = kpiId;
            ElementIdOption = elementId;
            IsAggregatedOption = isAggregated;
            OldValueOption = oldValue;
            NewValueOption = newValue;
            OldStatusOption = oldStatus;
            NewStatusOption = newStatus;
            IsImputedOption = isImputed;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Timestamp
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTimeOffset?> TimestampOption { get; private set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [JsonPropertyName("timestamp")]
        public DateTimeOffset? Timestamp { get { return this.TimestampOption; } set { this.TimestampOption = new(value); } }

        /// <summary>
        /// Used to track the state of SourceSystem
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SourceSystemOption { get; private set; }

        /// <summary>
        /// Gets or Sets SourceSystem
        /// </summary>
        [JsonPropertyName("sourceSystem")]
        public string? SourceSystem { get { return this.SourceSystemOption; } set { this.SourceSystemOption = new(value); } }

        /// <summary>
        /// Used to track the state of KpiId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> KpiIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets KpiId
        /// </summary>
        [JsonPropertyName("kpiId")]
        public string? KpiId { get { return this.KpiIdOption; } set { this.KpiIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ElementId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ElementIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ElementId
        /// </summary>
        [JsonPropertyName("elementId")]
        public string? ElementId { get { return this.ElementIdOption; } set { this.ElementIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsAggregated
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsAggregatedOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsAggregated
        /// </summary>
        [JsonPropertyName("isAggregated")]
        public bool? IsAggregated { get { return this.IsAggregatedOption; } set { this.IsAggregatedOption = new(value); } }

        /// <summary>
        /// Used to track the state of OldValue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OldValueOption { get; private set; }

        /// <summary>
        /// Gets or Sets OldValue
        /// </summary>
        [JsonPropertyName("oldValue")]
        public string? OldValue { get { return this.OldValueOption; } set { this.OldValueOption = new(value); } }

        /// <summary>
        /// Used to track the state of NewValue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NewValueOption { get; private set; }

        /// <summary>
        /// Gets or Sets NewValue
        /// </summary>
        [JsonPropertyName("newValue")]
        public string? NewValue { get { return this.NewValueOption; } set { this.NewValueOption = new(value); } }

        /// <summary>
        /// Used to track the state of OldStatus
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OldStatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets OldStatus
        /// </summary>
        [JsonPropertyName("oldStatus")]
        public string? OldStatus { get { return this.OldStatusOption; } set { this.OldStatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of NewStatus
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NewStatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets NewStatus
        /// </summary>
        [JsonPropertyName("newStatus")]
        public string? NewStatus { get { return this.NewStatusOption; } set { this.NewStatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsImputed
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsImputedOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsImputed
        /// </summary>
        [JsonPropertyName("isImputed")]
        public bool? IsImputed { get { return this.IsImputedOption; } set { this.IsImputedOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KpiHistoryResponse {\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  SourceSystem: ").Append(SourceSystem).Append("\n");
            sb.Append("  KpiId: ").Append(KpiId).Append("\n");
            sb.Append("  ElementId: ").Append(ElementId).Append("\n");
            sb.Append("  IsAggregated: ").Append(IsAggregated).Append("\n");
            sb.Append("  OldValue: ").Append(OldValue).Append("\n");
            sb.Append("  NewValue: ").Append(NewValue).Append("\n");
            sb.Append("  OldStatus: ").Append(OldStatus).Append("\n");
            sb.Append("  NewStatus: ").Append(NewStatus).Append("\n");
            sb.Append("  IsImputed: ").Append(IsImputed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="KpiHistoryResponse" />
    /// </summary>
    public class KpiHistoryResponseJsonConverter : JsonConverter<KpiHistoryResponse>
    {
        /// <summary>
        /// The format to use to serialize Timestamp
        /// </summary>
        public static string TimestampFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="KpiHistoryResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override KpiHistoryResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<DateTimeOffset?> timestamp = default;
            Option<string?> sourceSystem = default;
            Option<string?> kpiId = default;
            Option<string?> elementId = default;
            Option<bool?> isAggregated = default;
            Option<string?> oldValue = default;
            Option<string?> newValue = default;
            Option<string?> oldStatus = default;
            Option<string?> newStatus = default;
            Option<bool?> isImputed = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "timestamp":
                            timestamp = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "sourceSystem":
                            sourceSystem = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "kpiId":
                            kpiId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "elementId":
                            elementId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "isAggregated":
                            isAggregated = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "oldValue":
                            oldValue = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "newValue":
                            newValue = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "oldStatus":
                            oldStatus = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "newStatus":
                            newStatus = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "isImputed":
                            isImputed = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (timestamp.IsSet && timestamp.Value == null)
                throw new ArgumentNullException(nameof(timestamp), "Property is not nullable for class KpiHistoryResponse.");

            if (sourceSystem.IsSet && sourceSystem.Value == null)
                throw new ArgumentNullException(nameof(sourceSystem), "Property is not nullable for class KpiHistoryResponse.");

            if (kpiId.IsSet && kpiId.Value == null)
                throw new ArgumentNullException(nameof(kpiId), "Property is not nullable for class KpiHistoryResponse.");

            if (elementId.IsSet && elementId.Value == null)
                throw new ArgumentNullException(nameof(elementId), "Property is not nullable for class KpiHistoryResponse.");

            if (isAggregated.IsSet && isAggregated.Value == null)
                throw new ArgumentNullException(nameof(isAggregated), "Property is not nullable for class KpiHistoryResponse.");

            if (oldValue.IsSet && oldValue.Value == null)
                throw new ArgumentNullException(nameof(oldValue), "Property is not nullable for class KpiHistoryResponse.");

            if (newValue.IsSet && newValue.Value == null)
                throw new ArgumentNullException(nameof(newValue), "Property is not nullable for class KpiHistoryResponse.");

            if (oldStatus.IsSet && oldStatus.Value == null)
                throw new ArgumentNullException(nameof(oldStatus), "Property is not nullable for class KpiHistoryResponse.");

            if (newStatus.IsSet && newStatus.Value == null)
                throw new ArgumentNullException(nameof(newStatus), "Property is not nullable for class KpiHistoryResponse.");

            if (isImputed.IsSet && isImputed.Value == null)
                throw new ArgumentNullException(nameof(isImputed), "Property is not nullable for class KpiHistoryResponse.");

            return new KpiHistoryResponse(timestamp, sourceSystem, kpiId, elementId, isAggregated, oldValue, newValue, oldStatus, newStatus, isImputed);
        }

        /// <summary>
        /// Serializes a <see cref="KpiHistoryResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="kpiHistoryResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, KpiHistoryResponse kpiHistoryResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, kpiHistoryResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="KpiHistoryResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="kpiHistoryResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, KpiHistoryResponse kpiHistoryResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (kpiHistoryResponse.SourceSystemOption.IsSet && kpiHistoryResponse.SourceSystem == null)
                throw new ArgumentNullException(nameof(kpiHistoryResponse.SourceSystem), "Property is required for class KpiHistoryResponse.");

            if (kpiHistoryResponse.KpiIdOption.IsSet && kpiHistoryResponse.KpiId == null)
                throw new ArgumentNullException(nameof(kpiHistoryResponse.KpiId), "Property is required for class KpiHistoryResponse.");

            if (kpiHistoryResponse.ElementIdOption.IsSet && kpiHistoryResponse.ElementId == null)
                throw new ArgumentNullException(nameof(kpiHistoryResponse.ElementId), "Property is required for class KpiHistoryResponse.");

            if (kpiHistoryResponse.OldValueOption.IsSet && kpiHistoryResponse.OldValue == null)
                throw new ArgumentNullException(nameof(kpiHistoryResponse.OldValue), "Property is required for class KpiHistoryResponse.");

            if (kpiHistoryResponse.NewValueOption.IsSet && kpiHistoryResponse.NewValue == null)
                throw new ArgumentNullException(nameof(kpiHistoryResponse.NewValue), "Property is required for class KpiHistoryResponse.");

            if (kpiHistoryResponse.OldStatusOption.IsSet && kpiHistoryResponse.OldStatus == null)
                throw new ArgumentNullException(nameof(kpiHistoryResponse.OldStatus), "Property is required for class KpiHistoryResponse.");

            if (kpiHistoryResponse.NewStatusOption.IsSet && kpiHistoryResponse.NewStatus == null)
                throw new ArgumentNullException(nameof(kpiHistoryResponse.NewStatus), "Property is required for class KpiHistoryResponse.");

            if (kpiHistoryResponse.TimestampOption.IsSet)
                writer.WriteString("timestamp", kpiHistoryResponse.TimestampOption.Value!.Value.ToString(TimestampFormat));

            if (kpiHistoryResponse.SourceSystemOption.IsSet)
                writer.WriteString("sourceSystem", kpiHistoryResponse.SourceSystem);

            if (kpiHistoryResponse.KpiIdOption.IsSet)
                writer.WriteString("kpiId", kpiHistoryResponse.KpiId);

            if (kpiHistoryResponse.ElementIdOption.IsSet)
                writer.WriteString("elementId", kpiHistoryResponse.ElementId);

            if (kpiHistoryResponse.IsAggregatedOption.IsSet)
                writer.WriteBoolean("isAggregated", kpiHistoryResponse.IsAggregatedOption.Value!.Value);

            if (kpiHistoryResponse.OldValueOption.IsSet)
                writer.WriteString("oldValue", kpiHistoryResponse.OldValue);

            if (kpiHistoryResponse.NewValueOption.IsSet)
                writer.WriteString("newValue", kpiHistoryResponse.NewValue);

            if (kpiHistoryResponse.OldStatusOption.IsSet)
                writer.WriteString("oldStatus", kpiHistoryResponse.OldStatus);

            if (kpiHistoryResponse.NewStatusOption.IsSet)
                writer.WriteString("newStatus", kpiHistoryResponse.NewStatus);

            if (kpiHistoryResponse.IsImputedOption.IsSet)
                writer.WriteBoolean("isImputed", kpiHistoryResponse.IsImputedOption.Value!.Value);
        }
    }
}
