// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// Defines MeteringAndMonitoringStrategyStatus
    /// </summary>
    public enum MeteringAndMonitoringStrategyStatus
    {
        /// <summary>
        /// Enum InProgress for value: InProgress
        /// </summary>
        InProgress = 1,

        /// <summary>
        /// Enum Submitted for value: Submitted
        /// </summary>
        Submitted = 2,

        /// <summary>
        /// Enum Complete for value: Complete
        /// </summary>
        Complete = 3,

        /// <summary>
        /// Enum Archived for value: Archived
        /// </summary>
        Archived = 4,

        /// <summary>
        /// Enum ReadyToStart for value: ReadyToStart
        /// </summary>
        ReadyToStart = 5,

        /// <summary>
        /// Enum CannotStartYet for value: CannotStartYet
        /// </summary>
        CannotStartYet = 6,

        /// <summary>
        /// Enum Incomplete for value: Incomplete
        /// </summary>
        Incomplete = 7
    }

    /// <summary>
    /// Converts <see cref="MeteringAndMonitoringStrategyStatus"/> to and from the JSON value
    /// </summary>
    public static class MeteringAndMonitoringStrategyStatusValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="MeteringAndMonitoringStrategyStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static MeteringAndMonitoringStrategyStatus FromString(string value)
        {
            if (value.Equals("InProgress"))
                return MeteringAndMonitoringStrategyStatus.InProgress;

            if (value.Equals("Submitted"))
                return MeteringAndMonitoringStrategyStatus.Submitted;

            if (value.Equals("Complete"))
                return MeteringAndMonitoringStrategyStatus.Complete;

            if (value.Equals("Archived"))
                return MeteringAndMonitoringStrategyStatus.Archived;

            if (value.Equals("ReadyToStart"))
                return MeteringAndMonitoringStrategyStatus.ReadyToStart;

            if (value.Equals("CannotStartYet"))
                return MeteringAndMonitoringStrategyStatus.CannotStartYet;

            if (value.Equals("Incomplete"))
                return MeteringAndMonitoringStrategyStatus.Incomplete;

            throw new NotImplementedException($"Could not convert value to type MeteringAndMonitoringStrategyStatus: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="MeteringAndMonitoringStrategyStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static MeteringAndMonitoringStrategyStatus? FromStringOrDefault(string value)
        {
            if (value.Equals("InProgress"))
                return MeteringAndMonitoringStrategyStatus.InProgress;

            if (value.Equals("Submitted"))
                return MeteringAndMonitoringStrategyStatus.Submitted;

            if (value.Equals("Complete"))
                return MeteringAndMonitoringStrategyStatus.Complete;

            if (value.Equals("Archived"))
                return MeteringAndMonitoringStrategyStatus.Archived;

            if (value.Equals("ReadyToStart"))
                return MeteringAndMonitoringStrategyStatus.ReadyToStart;

            if (value.Equals("CannotStartYet"))
                return MeteringAndMonitoringStrategyStatus.CannotStartYet;

            if (value.Equals("Incomplete"))
                return MeteringAndMonitoringStrategyStatus.Incomplete;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="MeteringAndMonitoringStrategyStatus"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(MeteringAndMonitoringStrategyStatus value)
        {
            if (value == MeteringAndMonitoringStrategyStatus.InProgress)
                return "InProgress";

            if (value == MeteringAndMonitoringStrategyStatus.Submitted)
                return "Submitted";

            if (value == MeteringAndMonitoringStrategyStatus.Complete)
                return "Complete";

            if (value == MeteringAndMonitoringStrategyStatus.Archived)
                return "Archived";

            if (value == MeteringAndMonitoringStrategyStatus.ReadyToStart)
                return "ReadyToStart";

            if (value == MeteringAndMonitoringStrategyStatus.CannotStartYet)
                return "CannotStartYet";

            if (value == MeteringAndMonitoringStrategyStatus.Incomplete)
                return "Incomplete";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MeteringAndMonitoringStrategyStatus"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class MeteringAndMonitoringStrategyStatusJsonConverter : JsonConverter<MeteringAndMonitoringStrategyStatus>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override MeteringAndMonitoringStrategyStatus Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            MeteringAndMonitoringStrategyStatus? result = rawValue == null
                ? null
                : MeteringAndMonitoringStrategyStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the MeteringAndMonitoringStrategyStatus to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="meteringAndMonitoringStrategyStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, MeteringAndMonitoringStrategyStatus meteringAndMonitoringStrategyStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(MeteringAndMonitoringStrategyStatusValueConverter.ToJsonValue(meteringAndMonitoringStrategyStatus).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MeteringAndMonitoringStrategyStatus"/>
    /// </summary>
    public class MeteringAndMonitoringStrategyStatusNullableJsonConverter : JsonConverter<MeteringAndMonitoringStrategyStatus?>
    {
        /// <summary>
        /// Returns a MeteringAndMonitoringStrategyStatus from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override MeteringAndMonitoringStrategyStatus? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            MeteringAndMonitoringStrategyStatus? result = rawValue == null
                ? null
                : MeteringAndMonitoringStrategyStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the MeteringAndMonitoringStrategyStatus to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="meteringAndMonitoringStrategyStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, MeteringAndMonitoringStrategyStatus? meteringAndMonitoringStrategyStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(meteringAndMonitoringStrategyStatus.HasValue ? MeteringAndMonitoringStrategyStatusValueConverter.ToJsonValue(meteringAndMonitoringStrategyStatus.Value).ToString() : "null");
        }
    }
}
