// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// NetworkElement
    /// </summary>
    public partial class NetworkElement : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NetworkElement" /> class.
        /// </summary>
        /// <param name="elementId">elementId</param>
        /// <param name="type">type</param>
        /// <param name="kpis">kpis</param>
        [JsonConstructor]
        public NetworkElement(string elementId, ElementType type, Option<Dictionary<string, KpiValue>?> kpis = default)
        {
            ElementId = elementId;
            Type = type;
            KpisOption = kpis;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public ElementType Type { get; set; }

        /// <summary>
        /// Gets or Sets ElementId
        /// </summary>
        [JsonPropertyName("elementId")]
        public string ElementId { get; set; }

        /// <summary>
        /// Used to track the state of Kpis
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, KpiValue>?> KpisOption { get; private set; }

        /// <summary>
        /// Gets or Sets Kpis
        /// </summary>
        [JsonPropertyName("kpis")]
        public Dictionary<string, KpiValue>? Kpis { get { return this.KpisOption; } set { this.KpisOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NetworkElement {\n");
            sb.Append("  ElementId: ").Append(ElementId).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Kpis: ").Append(Kpis).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NetworkElement" />
    /// </summary>
    public class NetworkElementJsonConverter : JsonConverter<NetworkElement>
    {
        /// <summary>
        /// Deserializes json to <see cref="NetworkElement" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NetworkElement Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> elementId = default;
            Option<ElementType?> type = default;
            Option<Dictionary<string, KpiValue>?> kpis = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "elementId":
                            elementId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<ElementType?>(ElementTypeValueConverter.FromStringOrDefault(typeRawValue));
                            break;
                        case "kpis":
                            kpis = new Option<Dictionary<string, KpiValue>?>(JsonSerializer.Deserialize<Dictionary<string, KpiValue>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!elementId.IsSet)
                throw new ArgumentException("Property is required for class NetworkElement.", nameof(elementId));

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class NetworkElement.", nameof(type));

            if (elementId.IsSet && elementId.Value == null)
                throw new ArgumentNullException(nameof(elementId), "Property is not nullable for class NetworkElement.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class NetworkElement.");

            if (kpis.IsSet && kpis.Value == null)
                throw new ArgumentNullException(nameof(kpis), "Property is not nullable for class NetworkElement.");

            return new NetworkElement(elementId.Value!, type.Value!.Value!, kpis);
        }

        /// <summary>
        /// Serializes a <see cref="NetworkElement" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="networkElement"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, NetworkElement networkElement, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, networkElement, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="NetworkElement" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="networkElement"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, NetworkElement networkElement, JsonSerializerOptions jsonSerializerOptions)
        {
            if (networkElement.ElementId == null)
                throw new ArgumentNullException(nameof(networkElement.ElementId), "Property is required for class NetworkElement.");

            if (networkElement.KpisOption.IsSet && networkElement.Kpis == null)
                throw new ArgumentNullException(nameof(networkElement.Kpis), "Property is required for class NetworkElement.");

            writer.WriteString("elementId", networkElement.ElementId);

            var typeRawValue = ElementTypeValueConverter.ToJsonValue(networkElement.Type);
            writer.WriteString("type", typeRawValue);

            if (networkElement.KpisOption.IsSet)
            {
                writer.WritePropertyName("kpis");
                JsonSerializer.Serialize(writer, networkElement.Kpis, jsonSerializerOptions);
            }
        }
    }
}
