// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// Defines NetworkCharacteristicsStatus
    /// </summary>
    public enum NetworkCharacteristicsStatus
    {
        /// <summary>
        /// Enum InProgress for value: InProgress
        /// </summary>
        InProgress = 1,

        /// <summary>
        /// Enum Submitted for value: Submitted
        /// </summary>
        Submitted = 2,

        /// <summary>
        /// Enum Complete for value: Complete
        /// </summary>
        Complete = 3,

        /// <summary>
        /// Enum Archived for value: Archived
        /// </summary>
        Archived = 4,

        /// <summary>
        /// Enum ReadyToStart for value: ReadyToStart
        /// </summary>
        ReadyToStart = 5,

        /// <summary>
        /// Enum CannotStartYet for value: CannotStartYet
        /// </summary>
        CannotStartYet = 6,

        /// <summary>
        /// Enum Incomplete for value: Incomplete
        /// </summary>
        Incomplete = 7
    }

    /// <summary>
    /// Converts <see cref="NetworkCharacteristicsStatus"/> to and from the JSON value
    /// </summary>
    public static class NetworkCharacteristicsStatusValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="NetworkCharacteristicsStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static NetworkCharacteristicsStatus FromString(string value)
        {
            if (value.Equals("InProgress"))
                return NetworkCharacteristicsStatus.InProgress;

            if (value.Equals("Submitted"))
                return NetworkCharacteristicsStatus.Submitted;

            if (value.Equals("Complete"))
                return NetworkCharacteristicsStatus.Complete;

            if (value.Equals("Archived"))
                return NetworkCharacteristicsStatus.Archived;

            if (value.Equals("ReadyToStart"))
                return NetworkCharacteristicsStatus.ReadyToStart;

            if (value.Equals("CannotStartYet"))
                return NetworkCharacteristicsStatus.CannotStartYet;

            if (value.Equals("Incomplete"))
                return NetworkCharacteristicsStatus.Incomplete;

            throw new NotImplementedException($"Could not convert value to type NetworkCharacteristicsStatus: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="NetworkCharacteristicsStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static NetworkCharacteristicsStatus? FromStringOrDefault(string value)
        {
            if (value.Equals("InProgress"))
                return NetworkCharacteristicsStatus.InProgress;

            if (value.Equals("Submitted"))
                return NetworkCharacteristicsStatus.Submitted;

            if (value.Equals("Complete"))
                return NetworkCharacteristicsStatus.Complete;

            if (value.Equals("Archived"))
                return NetworkCharacteristicsStatus.Archived;

            if (value.Equals("ReadyToStart"))
                return NetworkCharacteristicsStatus.ReadyToStart;

            if (value.Equals("CannotStartYet"))
                return NetworkCharacteristicsStatus.CannotStartYet;

            if (value.Equals("Incomplete"))
                return NetworkCharacteristicsStatus.Incomplete;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="NetworkCharacteristicsStatus"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(NetworkCharacteristicsStatus value)
        {
            if (value == NetworkCharacteristicsStatus.InProgress)
                return "InProgress";

            if (value == NetworkCharacteristicsStatus.Submitted)
                return "Submitted";

            if (value == NetworkCharacteristicsStatus.Complete)
                return "Complete";

            if (value == NetworkCharacteristicsStatus.Archived)
                return "Archived";

            if (value == NetworkCharacteristicsStatus.ReadyToStart)
                return "ReadyToStart";

            if (value == NetworkCharacteristicsStatus.CannotStartYet)
                return "CannotStartYet";

            if (value == NetworkCharacteristicsStatus.Incomplete)
                return "Incomplete";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NetworkCharacteristicsStatus"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class NetworkCharacteristicsStatusJsonConverter : JsonConverter<NetworkCharacteristicsStatus>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override NetworkCharacteristicsStatus Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            NetworkCharacteristicsStatus? result = rawValue == null
                ? null
                : NetworkCharacteristicsStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the NetworkCharacteristicsStatus to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="networkCharacteristicsStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, NetworkCharacteristicsStatus networkCharacteristicsStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(NetworkCharacteristicsStatusValueConverter.ToJsonValue(networkCharacteristicsStatus).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NetworkCharacteristicsStatus"/>
    /// </summary>
    public class NetworkCharacteristicsStatusNullableJsonConverter : JsonConverter<NetworkCharacteristicsStatus?>
    {
        /// <summary>
        /// Returns a NetworkCharacteristicsStatus from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override NetworkCharacteristicsStatus? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            NetworkCharacteristicsStatus? result = rawValue == null
                ? null
                : NetworkCharacteristicsStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the NetworkCharacteristicsStatus to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="networkCharacteristicsStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, NetworkCharacteristicsStatus? networkCharacteristicsStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(networkCharacteristicsStatus.HasValue ? NetworkCharacteristicsStatusValueConverter.ToJsonValue(networkCharacteristicsStatus.Value).ToString() : "null");
        }
    }
}
