// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// OrgDetails2
    /// </summary>
    public partial class OrgDetails2 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrgDetails2" /> class.
        /// </summary>
        /// <param name="orgType">orgType</param>
        /// <param name="orgName">orgName</param>
        /// <param name="firstName">firstName</param>
        /// <param name="lastName">lastName</param>
        /// <param name="preferredContactType">preferredContactType</param>
        /// <param name="orgRegisteredAddress">orgRegisteredAddress</param>
        /// <param name="orgId">orgId</param>
        /// <param name="companiesHouseNumber">companiesHouseNumber</param>
        /// <param name="landlineNumber">landlineNumber</param>
        /// <param name="contactNumberExtension">contactNumberExtension</param>
        /// <param name="mobileNumber">mobileNumber</param>
        /// <param name="jobTitle">jobTitle</param>
        [JsonConstructor]
        public OrgDetails2(OrganisationType orgType, string orgName, string firstName, string lastName, PreferredContactType preferredContactType, OrgRegisteredAddress orgRegisteredAddress, Option<string?> orgId = default, Option<string?> companiesHouseNumber = default, Option<string?> landlineNumber = default, Option<string?> contactNumberExtension = default, Option<string?> mobileNumber = default, string? jobTitle = default)
        {
            OrgType = orgType;
            OrgName = orgName;
            FirstName = firstName;
            LastName = lastName;
            PreferredContactType = preferredContactType;
            OrgRegisteredAddress = orgRegisteredAddress;
            OrgIdOption = orgId;
            CompaniesHouseNumberOption = companiesHouseNumber;
            LandlineNumberOption = landlineNumber;
            ContactNumberExtensionOption = contactNumberExtension;
            MobileNumberOption = mobileNumber;
            JobTitle = jobTitle;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets OrgType
        /// </summary>
        [JsonPropertyName("orgType")]
        public OrganisationType OrgType { get; set; }

        /// <summary>
        /// Gets or Sets PreferredContactType
        /// </summary>
        [JsonPropertyName("preferredContactType")]
        public PreferredContactType PreferredContactType { get; set; }

        /// <summary>
        /// Gets or Sets OrgName
        /// </summary>
        [JsonPropertyName("orgName")]
        public string OrgName { get; set; }

        /// <summary>
        /// Gets or Sets FirstName
        /// </summary>
        [JsonPropertyName("firstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// Gets or Sets LastName
        /// </summary>
        [JsonPropertyName("lastName")]
        public string LastName { get; set; }

        /// <summary>
        /// Gets or Sets OrgRegisteredAddress
        /// </summary>
        [JsonPropertyName("orgRegisteredAddress")]
        public OrgRegisteredAddress OrgRegisteredAddress { get; set; }

        /// <summary>
        /// Used to track the state of OrgId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OrgIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets OrgId
        /// </summary>
        [JsonPropertyName("orgId")]
        public string? OrgId { get { return this.OrgIdOption; } set { this.OrgIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of CompaniesHouseNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CompaniesHouseNumberOption { get; private set; }

        /// <summary>
        /// Gets or Sets CompaniesHouseNumber
        /// </summary>
        [JsonPropertyName("companiesHouseNumber")]
        public string? CompaniesHouseNumber { get { return this.CompaniesHouseNumberOption; } set { this.CompaniesHouseNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of LandlineNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LandlineNumberOption { get; private set; }

        /// <summary>
        /// Gets or Sets LandlineNumber
        /// </summary>
        [JsonPropertyName("landlineNumber")]
        public string? LandlineNumber { get { return this.LandlineNumberOption; } set { this.LandlineNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of ContactNumberExtension
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ContactNumberExtensionOption { get; private set; }

        /// <summary>
        /// Gets or Sets ContactNumberExtension
        /// </summary>
        [JsonPropertyName("contactNumberExtension")]
        public string? ContactNumberExtension { get { return this.ContactNumberExtensionOption; } set { this.ContactNumberExtensionOption = new(value); } }

        /// <summary>
        /// Used to track the state of MobileNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MobileNumberOption { get; private set; }

        /// <summary>
        /// Gets or Sets MobileNumber
        /// </summary>
        [JsonPropertyName("mobileNumber")]
        public string? MobileNumber { get { return this.MobileNumberOption; } set { this.MobileNumberOption = new(value); } }

        /// <summary>
        /// Gets or Sets JobTitle
        /// </summary>
        [JsonPropertyName("jobTitle")]
        public string? JobTitle { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrgDetails2 {\n");
            sb.Append("  OrgType: ").Append(OrgType).Append("\n");
            sb.Append("  OrgName: ").Append(OrgName).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  PreferredContactType: ").Append(PreferredContactType).Append("\n");
            sb.Append("  OrgRegisteredAddress: ").Append(OrgRegisteredAddress).Append("\n");
            sb.Append("  OrgId: ").Append(OrgId).Append("\n");
            sb.Append("  CompaniesHouseNumber: ").Append(CompaniesHouseNumber).Append("\n");
            sb.Append("  LandlineNumber: ").Append(LandlineNumber).Append("\n");
            sb.Append("  ContactNumberExtension: ").Append(ContactNumberExtension).Append("\n");
            sb.Append("  MobileNumber: ").Append(MobileNumber).Append("\n");
            sb.Append("  JobTitle: ").Append(JobTitle).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // LandlineNumber (string) maxLength
            if (this.LandlineNumber != null && this.LandlineNumber.Length > 20)
            {
                yield return new ValidationResult("Invalid value for LandlineNumber, length must be less than 20.", new [] { "LandlineNumber" });
            }

            if (this.LandlineNumberOption.Value != null) {
                // LandlineNumber (string) pattern
                Regex regexLandlineNumber = new Regex(@"^\+?\d{1,3}[\s-]?\(?\d{1,4}\)?[\s-]?\d{1,4}[\s-]?\d{1,4}[\s-]?\d{1,9}$", RegexOptions.CultureInvariant);

                if (this.LandlineNumberOption.Value != null &&!regexLandlineNumber.Match(this.LandlineNumberOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for LandlineNumber, must match a pattern of " + regexLandlineNumber, new [] { "LandlineNumber" });
                }
            }

            // ContactNumberExtension (string) maxLength
            if (this.ContactNumberExtension != null && this.ContactNumberExtension.Length > 10)
            {
                yield return new ValidationResult("Invalid value for ContactNumberExtension, length must be less than 10.", new [] { "ContactNumberExtension" });
            }

            if (this.ContactNumberExtensionOption.Value != null) {
                // ContactNumberExtension (string) pattern
                Regex regexContactNumberExtension = new Regex(@"^\d*$", RegexOptions.CultureInvariant);

                if (this.ContactNumberExtensionOption.Value != null &&!regexContactNumberExtension.Match(this.ContactNumberExtensionOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ContactNumberExtension, must match a pattern of " + regexContactNumberExtension, new [] { "ContactNumberExtension" });
                }
            }

            // MobileNumber (string) maxLength
            if (this.MobileNumber != null && this.MobileNumber.Length > 13)
            {
                yield return new ValidationResult("Invalid value for MobileNumber, length must be less than 13.", new [] { "MobileNumber" });
            }

            if (this.MobileNumberOption.Value != null) {
                // MobileNumber (string) pattern
                Regex regexMobileNumber = new Regex(@"^\+?\d{1,3}[\s-]?\(?\d{1,4}\)?[\s-]?\d{1,4}[\s-]?\d{1,4}[\s-]?\d{1,9}$", RegexOptions.CultureInvariant);

                if (this.MobileNumberOption.Value != null &&!regexMobileNumber.Match(this.MobileNumberOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MobileNumber, must match a pattern of " + regexMobileNumber, new [] { "MobileNumber" });
                }
            }

            // JobTitle (string) maxLength
            if (this.JobTitle != null && this.JobTitle.Length > 100)
            {
                yield return new ValidationResult("Invalid value for JobTitle, length must be less than 100.", new [] { "JobTitle" });
            }

            if (this.JobTitle != null) {
                // JobTitle (string) pattern
                Regex regexJobTitle = new Regex(@"^[a-zA-Z ]+$", RegexOptions.CultureInvariant);

                if (this.JobTitle != null && !regexJobTitle.Match(this.JobTitle).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for JobTitle, must match a pattern of " + regexJobTitle, new [] { "JobTitle" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OrgDetails2" />
    /// </summary>
    public class OrgDetails2JsonConverter : JsonConverter<OrgDetails2>
    {
        /// <summary>
        /// Deserializes json to <see cref="OrgDetails2" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OrgDetails2 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<OrganisationType?> orgType = default;
            Option<string?> orgName = default;
            Option<string?> firstName = default;
            Option<string?> lastName = default;
            Option<PreferredContactType?> preferredContactType = default;
            Option<OrgRegisteredAddress?> orgRegisteredAddress = default;
            Option<string?> orgId = default;
            Option<string?> companiesHouseNumber = default;
            Option<string?> landlineNumber = default;
            Option<string?> contactNumberExtension = default;
            Option<string?> mobileNumber = default;
            Option<string?> jobTitle = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "orgType":
                            string? orgTypeRawValue = utf8JsonReader.GetString();
                            if (orgTypeRawValue != null)
                                orgType = new Option<OrganisationType?>(OrganisationTypeValueConverter.FromStringOrDefault(orgTypeRawValue));
                            break;
                        case "orgName":
                            orgName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "firstName":
                            firstName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "lastName":
                            lastName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "preferredContactType":
                            string? preferredContactTypeRawValue = utf8JsonReader.GetString();
                            if (preferredContactTypeRawValue != null)
                                preferredContactType = new Option<PreferredContactType?>(PreferredContactTypeValueConverter.FromStringOrDefault(preferredContactTypeRawValue));
                            break;
                        case "orgRegisteredAddress":
                            orgRegisteredAddress = new Option<OrgRegisteredAddress?>(JsonSerializer.Deserialize<OrgRegisteredAddress>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "orgId":
                            orgId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "companiesHouseNumber":
                            companiesHouseNumber = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "landlineNumber":
                            landlineNumber = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "contactNumberExtension":
                            contactNumberExtension = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "mobileNumber":
                            mobileNumber = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "jobTitle":
                            jobTitle = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!orgType.IsSet)
                throw new ArgumentException("Property is required for class OrgDetails2.", nameof(orgType));

            if (!orgName.IsSet)
                throw new ArgumentException("Property is required for class OrgDetails2.", nameof(orgName));

            if (!firstName.IsSet)
                throw new ArgumentException("Property is required for class OrgDetails2.", nameof(firstName));

            if (!lastName.IsSet)
                throw new ArgumentException("Property is required for class OrgDetails2.", nameof(lastName));

            if (!preferredContactType.IsSet)
                throw new ArgumentException("Property is required for class OrgDetails2.", nameof(preferredContactType));

            if (!orgRegisteredAddress.IsSet)
                throw new ArgumentException("Property is required for class OrgDetails2.", nameof(orgRegisteredAddress));

            if (!jobTitle.IsSet)
                throw new ArgumentException("Property is required for class OrgDetails2.", nameof(jobTitle));

            if (orgType.IsSet && orgType.Value == null)
                throw new ArgumentNullException(nameof(orgType), "Property is not nullable for class OrgDetails2.");

            if (orgName.IsSet && orgName.Value == null)
                throw new ArgumentNullException(nameof(orgName), "Property is not nullable for class OrgDetails2.");

            if (firstName.IsSet && firstName.Value == null)
                throw new ArgumentNullException(nameof(firstName), "Property is not nullable for class OrgDetails2.");

            if (lastName.IsSet && lastName.Value == null)
                throw new ArgumentNullException(nameof(lastName), "Property is not nullable for class OrgDetails2.");

            if (preferredContactType.IsSet && preferredContactType.Value == null)
                throw new ArgumentNullException(nameof(preferredContactType), "Property is not nullable for class OrgDetails2.");

            if (orgRegisteredAddress.IsSet && orgRegisteredAddress.Value == null)
                throw new ArgumentNullException(nameof(orgRegisteredAddress), "Property is not nullable for class OrgDetails2.");

            return new OrgDetails2(orgType.Value!.Value!, orgName.Value!, firstName.Value!, lastName.Value!, preferredContactType.Value!.Value!, orgRegisteredAddress.Value!, orgId, companiesHouseNumber, landlineNumber, contactNumberExtension, mobileNumber, jobTitle.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="OrgDetails2" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="orgDetails2"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OrgDetails2 orgDetails2, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, orgDetails2, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OrgDetails2" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="orgDetails2"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OrgDetails2 orgDetails2, JsonSerializerOptions jsonSerializerOptions)
        {
            if (orgDetails2.OrgName == null)
                throw new ArgumentNullException(nameof(orgDetails2.OrgName), "Property is required for class OrgDetails2.");

            if (orgDetails2.FirstName == null)
                throw new ArgumentNullException(nameof(orgDetails2.FirstName), "Property is required for class OrgDetails2.");

            if (orgDetails2.LastName == null)
                throw new ArgumentNullException(nameof(orgDetails2.LastName), "Property is required for class OrgDetails2.");

            if (orgDetails2.OrgRegisteredAddress == null)
                throw new ArgumentNullException(nameof(orgDetails2.OrgRegisteredAddress), "Property is required for class OrgDetails2.");

            var orgTypeRawValue = OrganisationTypeValueConverter.ToJsonValue(orgDetails2.OrgType);
            writer.WriteString("orgType", orgTypeRawValue);

            writer.WriteString("orgName", orgDetails2.OrgName);

            writer.WriteString("firstName", orgDetails2.FirstName);

            writer.WriteString("lastName", orgDetails2.LastName);

            var preferredContactTypeRawValue = PreferredContactTypeValueConverter.ToJsonValue(orgDetails2.PreferredContactType);
            writer.WriteString("preferredContactType", preferredContactTypeRawValue);

            writer.WritePropertyName("orgRegisteredAddress");
            JsonSerializer.Serialize(writer, orgDetails2.OrgRegisteredAddress, jsonSerializerOptions);
            if (orgDetails2.OrgIdOption.IsSet)
                if (orgDetails2.OrgIdOption.Value != null)
                    writer.WriteString("orgId", orgDetails2.OrgId);
                else
                    writer.WriteNull("orgId");

            if (orgDetails2.CompaniesHouseNumberOption.IsSet)
                if (orgDetails2.CompaniesHouseNumberOption.Value != null)
                    writer.WriteString("companiesHouseNumber", orgDetails2.CompaniesHouseNumber);
                else
                    writer.WriteNull("companiesHouseNumber");

            if (orgDetails2.LandlineNumberOption.IsSet)
                if (orgDetails2.LandlineNumberOption.Value != null)
                    writer.WriteString("landlineNumber", orgDetails2.LandlineNumber);
                else
                    writer.WriteNull("landlineNumber");

            if (orgDetails2.ContactNumberExtensionOption.IsSet)
                if (orgDetails2.ContactNumberExtensionOption.Value != null)
                    writer.WriteString("contactNumberExtension", orgDetails2.ContactNumberExtension);
                else
                    writer.WriteNull("contactNumberExtension");

            if (orgDetails2.MobileNumberOption.IsSet)
                if (orgDetails2.MobileNumberOption.Value != null)
                    writer.WriteString("mobileNumber", orgDetails2.MobileNumber);
                else
                    writer.WriteNull("mobileNumber");

            if (orgDetails2.JobTitle != null)
                writer.WriteString("jobTitle", orgDetails2.JobTitle);
            else
                writer.WriteNull("jobTitle");
        }
    }
}
