// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// SOAAssesorEmailRequest
    /// </summary>
    public partial class SOAAssesorEmailRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SOAAssesorEmailRequest" /> class.
        /// </summary>
        /// <param name="hnId">hnId</param>
        /// <param name="hnName">hnName</param>
        /// <param name="phase">phase</param>
        /// <param name="stageNumber">stageNumber</param>
        /// <param name="stageName">stageName</param>
        /// <param name="contributorName">contributorName</param>
        [JsonConstructor]
        public SOAAssesorEmailRequest(Option<string?> hnId = default, Option<string?> hnName = default, Option<string?> phase = default, Option<string?> stageNumber = default, Option<string?> stageName = default, Option<string?> contributorName = default)
        {
            HnIdOption = hnId;
            HnNameOption = hnName;
            PhaseOption = phase;
            StageNumberOption = stageNumber;
            StageNameOption = stageName;
            ContributorNameOption = contributorName;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of HnId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> HnIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets HnId
        /// </summary>
        [JsonPropertyName("hnId")]
        public string? HnId { get { return this.HnIdOption; } set { this.HnIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of HnName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> HnNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets HnName
        /// </summary>
        [JsonPropertyName("hnName")]
        public string? HnName { get { return this.HnNameOption; } set { this.HnNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Phase
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PhaseOption { get; private set; }

        /// <summary>
        /// Gets or Sets Phase
        /// </summary>
        [JsonPropertyName("phase")]
        public string? Phase { get { return this.PhaseOption; } set { this.PhaseOption = new(value); } }

        /// <summary>
        /// Used to track the state of StageNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StageNumberOption { get; private set; }

        /// <summary>
        /// Gets or Sets StageNumber
        /// </summary>
        [JsonPropertyName("stageNumber")]
        public string? StageNumber { get { return this.StageNumberOption; } set { this.StageNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of StageName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StageNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets StageName
        /// </summary>
        [JsonPropertyName("stageName")]
        public string? StageName { get { return this.StageNameOption; } set { this.StageNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of ContributorName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ContributorNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets ContributorName
        /// </summary>
        [JsonPropertyName("contributorName")]
        public string? ContributorName { get { return this.ContributorNameOption; } set { this.ContributorNameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SOAAssesorEmailRequest {\n");
            sb.Append("  HnId: ").Append(HnId).Append("\n");
            sb.Append("  HnName: ").Append(HnName).Append("\n");
            sb.Append("  Phase: ").Append(Phase).Append("\n");
            sb.Append("  StageNumber: ").Append(StageNumber).Append("\n");
            sb.Append("  StageName: ").Append(StageName).Append("\n");
            sb.Append("  ContributorName: ").Append(ContributorName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SOAAssesorEmailRequest" />
    /// </summary>
    public class SOAAssesorEmailRequestJsonConverter : JsonConverter<SOAAssesorEmailRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="SOAAssesorEmailRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SOAAssesorEmailRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> hnId = default;
            Option<string?> hnName = default;
            Option<string?> phase = default;
            Option<string?> stageNumber = default;
            Option<string?> stageName = default;
            Option<string?> contributorName = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "hnId":
                            hnId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "hnName":
                            hnName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "phase":
                            phase = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "stageNumber":
                            stageNumber = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "stageName":
                            stageName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "contributorName":
                            contributorName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (hnId.IsSet && hnId.Value == null)
                throw new ArgumentNullException(nameof(hnId), "Property is not nullable for class SOAAssesorEmailRequest.");

            if (hnName.IsSet && hnName.Value == null)
                throw new ArgumentNullException(nameof(hnName), "Property is not nullable for class SOAAssesorEmailRequest.");

            if (phase.IsSet && phase.Value == null)
                throw new ArgumentNullException(nameof(phase), "Property is not nullable for class SOAAssesorEmailRequest.");

            if (stageNumber.IsSet && stageNumber.Value == null)
                throw new ArgumentNullException(nameof(stageNumber), "Property is not nullable for class SOAAssesorEmailRequest.");

            if (stageName.IsSet && stageName.Value == null)
                throw new ArgumentNullException(nameof(stageName), "Property is not nullable for class SOAAssesorEmailRequest.");

            if (contributorName.IsSet && contributorName.Value == null)
                throw new ArgumentNullException(nameof(contributorName), "Property is not nullable for class SOAAssesorEmailRequest.");

            return new SOAAssesorEmailRequest(hnId, hnName, phase, stageNumber, stageName, contributorName);
        }

        /// <summary>
        /// Serializes a <see cref="SOAAssesorEmailRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sOAAssesorEmailRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SOAAssesorEmailRequest sOAAssesorEmailRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, sOAAssesorEmailRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SOAAssesorEmailRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sOAAssesorEmailRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SOAAssesorEmailRequest sOAAssesorEmailRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (sOAAssesorEmailRequest.HnIdOption.IsSet && sOAAssesorEmailRequest.HnId == null)
                throw new ArgumentNullException(nameof(sOAAssesorEmailRequest.HnId), "Property is required for class SOAAssesorEmailRequest.");

            if (sOAAssesorEmailRequest.HnNameOption.IsSet && sOAAssesorEmailRequest.HnName == null)
                throw new ArgumentNullException(nameof(sOAAssesorEmailRequest.HnName), "Property is required for class SOAAssesorEmailRequest.");

            if (sOAAssesorEmailRequest.PhaseOption.IsSet && sOAAssesorEmailRequest.Phase == null)
                throw new ArgumentNullException(nameof(sOAAssesorEmailRequest.Phase), "Property is required for class SOAAssesorEmailRequest.");

            if (sOAAssesorEmailRequest.StageNumberOption.IsSet && sOAAssesorEmailRequest.StageNumber == null)
                throw new ArgumentNullException(nameof(sOAAssesorEmailRequest.StageNumber), "Property is required for class SOAAssesorEmailRequest.");

            if (sOAAssesorEmailRequest.StageNameOption.IsSet && sOAAssesorEmailRequest.StageName == null)
                throw new ArgumentNullException(nameof(sOAAssesorEmailRequest.StageName), "Property is required for class SOAAssesorEmailRequest.");

            if (sOAAssesorEmailRequest.ContributorNameOption.IsSet && sOAAssesorEmailRequest.ContributorName == null)
                throw new ArgumentNullException(nameof(sOAAssesorEmailRequest.ContributorName), "Property is required for class SOAAssesorEmailRequest.");

            if (sOAAssesorEmailRequest.HnIdOption.IsSet)
                writer.WriteString("hnId", sOAAssesorEmailRequest.HnId);

            if (sOAAssesorEmailRequest.HnNameOption.IsSet)
                writer.WriteString("hnName", sOAAssesorEmailRequest.HnName);

            if (sOAAssesorEmailRequest.PhaseOption.IsSet)
                writer.WriteString("phase", sOAAssesorEmailRequest.Phase);

            if (sOAAssesorEmailRequest.StageNumberOption.IsSet)
                writer.WriteString("stageNumber", sOAAssesorEmailRequest.StageNumber);

            if (sOAAssesorEmailRequest.StageNameOption.IsSet)
                writer.WriteString("stageName", sOAAssesorEmailRequest.StageName);

            if (sOAAssesorEmailRequest.ContributorNameOption.IsSet)
                writer.WriteString("contributorName", sOAAssesorEmailRequest.ContributorName);
        }
    }
}
