// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// SoaJourneyData
    /// </summary>
    public partial class SoaJourneyData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SoaJourneyData" /> class.
        /// </summary>
        /// <param name="networkType">networkType</param>
        /// <param name="connectionTypes">connectionTypes</param>
        /// <param name="heatNetworkElements">heatNetworkElements</param>
        /// <param name="assessmentPlans">assessmentPlans</param>
        [JsonConstructor]
        public SoaJourneyData(Option<NetworkTypeSelection?> networkType = default, Option<List<ConnectionType>?> connectionTypes = default, Option<List<HeatNetworkElement>?> heatNetworkElements = default, Option<List<AssessmentPlanDocument>?> assessmentPlans = default)
        {
            NetworkTypeOption = networkType;
            ConnectionTypesOption = connectionTypes;
            HeatNetworkElementsOption = heatNetworkElements;
            AssessmentPlansOption = assessmentPlans;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of NetworkType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<NetworkTypeSelection?> NetworkTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets NetworkType
        /// </summary>
        [JsonPropertyName("networkType")]
        public NetworkTypeSelection? NetworkType { get { return this.NetworkTypeOption; } set { this.NetworkTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of ConnectionTypes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ConnectionType>?> ConnectionTypesOption { get; private set; }

        /// <summary>
        /// Gets or Sets ConnectionTypes
        /// </summary>
        [JsonPropertyName("connectionTypes")]
        public List<ConnectionType>? ConnectionTypes { get { return this.ConnectionTypesOption; } set { this.ConnectionTypesOption = new(value); } }

        /// <summary>
        /// Used to track the state of HeatNetworkElements
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<HeatNetworkElement>?> HeatNetworkElementsOption { get; private set; }

        /// <summary>
        /// Gets or Sets HeatNetworkElements
        /// </summary>
        [JsonPropertyName("heatNetworkElements")]
        public List<HeatNetworkElement>? HeatNetworkElements { get { return this.HeatNetworkElementsOption; } set { this.HeatNetworkElementsOption = new(value); } }

        /// <summary>
        /// Used to track the state of AssessmentPlans
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<AssessmentPlanDocument>?> AssessmentPlansOption { get; private set; }

        /// <summary>
        /// Gets or Sets AssessmentPlans
        /// </summary>
        [JsonPropertyName("assessmentPlans")]
        public List<AssessmentPlanDocument>? AssessmentPlans { get { return this.AssessmentPlansOption; } set { this.AssessmentPlansOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SoaJourneyData {\n");
            sb.Append("  NetworkType: ").Append(NetworkType).Append("\n");
            sb.Append("  ConnectionTypes: ").Append(ConnectionTypes).Append("\n");
            sb.Append("  HeatNetworkElements: ").Append(HeatNetworkElements).Append("\n");
            sb.Append("  AssessmentPlans: ").Append(AssessmentPlans).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SoaJourneyData" />
    /// </summary>
    public class SoaJourneyDataJsonConverter : JsonConverter<SoaJourneyData>
    {
        /// <summary>
        /// Deserializes json to <see cref="SoaJourneyData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SoaJourneyData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<NetworkTypeSelection?> networkType = default;
            Option<List<ConnectionType>?> connectionTypes = default;
            Option<List<HeatNetworkElement>?> heatNetworkElements = default;
            Option<List<AssessmentPlanDocument>?> assessmentPlans = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "networkType":
                            networkType = new Option<NetworkTypeSelection?>(JsonSerializer.Deserialize<NetworkTypeSelection>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "connectionTypes":
                            connectionTypes = new Option<List<ConnectionType>?>(JsonSerializer.Deserialize<List<ConnectionType>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "heatNetworkElements":
                            heatNetworkElements = new Option<List<HeatNetworkElement>?>(JsonSerializer.Deserialize<List<HeatNetworkElement>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "assessmentPlans":
                            assessmentPlans = new Option<List<AssessmentPlanDocument>?>(JsonSerializer.Deserialize<List<AssessmentPlanDocument>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (heatNetworkElements.IsSet && heatNetworkElements.Value == null)
                throw new ArgumentNullException(nameof(heatNetworkElements), "Property is not nullable for class SoaJourneyData.");

            if (assessmentPlans.IsSet && assessmentPlans.Value == null)
                throw new ArgumentNullException(nameof(assessmentPlans), "Property is not nullable for class SoaJourneyData.");

            return new SoaJourneyData(networkType, connectionTypes, heatNetworkElements, assessmentPlans);
        }

        /// <summary>
        /// Serializes a <see cref="SoaJourneyData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="soaJourneyData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SoaJourneyData soaJourneyData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, soaJourneyData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SoaJourneyData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="soaJourneyData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SoaJourneyData soaJourneyData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (soaJourneyData.HeatNetworkElementsOption.IsSet && soaJourneyData.HeatNetworkElements == null)
                throw new ArgumentNullException(nameof(soaJourneyData.HeatNetworkElements), "Property is required for class SoaJourneyData.");

            if (soaJourneyData.AssessmentPlansOption.IsSet && soaJourneyData.AssessmentPlans == null)
                throw new ArgumentNullException(nameof(soaJourneyData.AssessmentPlans), "Property is required for class SoaJourneyData.");

            if (soaJourneyData.NetworkTypeOption.IsSet)
                if (soaJourneyData.NetworkTypeOption.Value != null)
                {
                    writer.WritePropertyName("networkType");
                    JsonSerializer.Serialize(writer, soaJourneyData.NetworkType, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("networkType");
            if (soaJourneyData.ConnectionTypesOption.IsSet)
                if (soaJourneyData.ConnectionTypesOption.Value != null)
                {
                    writer.WritePropertyName("connectionTypes");
                    JsonSerializer.Serialize(writer, soaJourneyData.ConnectionTypes, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("connectionTypes");
            if (soaJourneyData.HeatNetworkElementsOption.IsSet)
            {
                writer.WritePropertyName("heatNetworkElements");
                JsonSerializer.Serialize(writer, soaJourneyData.HeatNetworkElements, jsonSerializerOptions);
            }
            if (soaJourneyData.AssessmentPlansOption.IsSet)
            {
                writer.WritePropertyName("assessmentPlans");
                JsonSerializer.Serialize(writer, soaJourneyData.AssessmentPlans, jsonSerializerOptions);
            }
        }
    }
}
