// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// SoaPhases
    /// </summary>
    public partial class SoaPhases : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SoaPhases" /> class.
        /// </summary>
        /// <param name="phase">phase</param>
        /// <param name="elements">elements</param>
        [JsonConstructor]
        public SoaPhases(Option<SoaPhase?> phase = default, Option<List<Elements>?> elements = default)
        {
            PhaseOption = phase;
            ElementsOption = elements;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Phase
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SoaPhase?> PhaseOption { get; private set; }

        /// <summary>
        /// Gets or Sets Phase
        /// </summary>
        [JsonPropertyName("phase")]
        public SoaPhase? Phase { get { return this.PhaseOption; } set { this.PhaseOption = new(value); } }

        /// <summary>
        /// Used to track the state of Elements
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Elements>?> ElementsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Elements
        /// </summary>
        [JsonPropertyName("elements")]
        public List<Elements>? Elements { get { return this.ElementsOption; } set { this.ElementsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SoaPhases {\n");
            sb.Append("  Phase: ").Append(Phase).Append("\n");
            sb.Append("  Elements: ").Append(Elements).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SoaPhases" />
    /// </summary>
    public class SoaPhasesJsonConverter : JsonConverter<SoaPhases>
    {
        /// <summary>
        /// Deserializes json to <see cref="SoaPhases" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SoaPhases Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<SoaPhase?> phase = default;
            Option<List<Elements>?> elements = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "phase":
                            string? phaseRawValue = utf8JsonReader.GetString();
                            if (phaseRawValue != null)
                                phase = new Option<SoaPhase?>(SoaPhaseValueConverter.FromStringOrDefault(phaseRawValue));
                            break;
                        case "elements":
                            elements = new Option<List<Elements>?>(JsonSerializer.Deserialize<List<Elements>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (phase.IsSet && phase.Value == null)
                throw new ArgumentNullException(nameof(phase), "Property is not nullable for class SoaPhases.");

            if (elements.IsSet && elements.Value == null)
                throw new ArgumentNullException(nameof(elements), "Property is not nullable for class SoaPhases.");

            return new SoaPhases(phase, elements);
        }

        /// <summary>
        /// Serializes a <see cref="SoaPhases" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="soaPhases"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SoaPhases soaPhases, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, soaPhases, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SoaPhases" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="soaPhases"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SoaPhases soaPhases, JsonSerializerOptions jsonSerializerOptions)
        {
            if (soaPhases.ElementsOption.IsSet && soaPhases.Elements == null)
                throw new ArgumentNullException(nameof(soaPhases.Elements), "Property is required for class SoaPhases.");

            if (soaPhases.PhaseOption.IsSet)
            {
                var phaseRawValue = SoaPhaseValueConverter.ToJsonValue(soaPhases.Phase!.Value);
                writer.WriteString("phase", phaseRawValue);
            }
            if (soaPhases.ElementsOption.IsSet)
            {
                writer.WritePropertyName("elements");
                JsonSerializer.Serialize(writer, soaPhases.Elements, jsonSerializerOptions);
            }
        }
    }
}
