// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// SoaResponse
    /// </summary>
    public partial class SoaResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SoaResponse" /> class.
        /// </summary>
        /// <param name="status">status</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="createdBy">createdBy</param>
        /// <param name="updatedAt">updatedAt</param>
        /// <param name="updatedBy">updatedBy</param>
        /// <param name="journeyData">journeyData</param>
        [JsonConstructor]
        public SoaResponse(Option<SoaStatus?> status = default, Option<DateTimeOffset?> createdAt = default, Option<string?> createdBy = default, Option<DateTimeOffset?> updatedAt = default, Option<string?> updatedBy = default, Option<JourneyDataResponse?> journeyData = default)
        {
            StatusOption = status;
            CreatedAtOption = createdAt;
            CreatedByOption = createdBy;
            UpdatedAtOption = updatedAt;
            UpdatedByOption = updatedBy;
            JourneyDataOption = journeyData;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SoaStatus?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public SoaStatus? Status { get { return this.StatusOption; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of CreatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTimeOffset?> CreatedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("createdAt")]
        public DateTimeOffset? CreatedAt { get { return this.CreatedAtOption; } set { this.CreatedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of CreatedBy
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CreatedByOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreatedBy
        /// </summary>
        [JsonPropertyName("createdBy")]
        public string? CreatedBy { get { return this.CreatedByOption; } set { this.CreatedByOption = new(value); } }

        /// <summary>
        /// Used to track the state of UpdatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTimeOffset?> UpdatedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [JsonPropertyName("updatedAt")]
        public DateTimeOffset? UpdatedAt { get { return this.UpdatedAtOption; } set { this.UpdatedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of UpdatedBy
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UpdatedByOption { get; private set; }

        /// <summary>
        /// Gets or Sets UpdatedBy
        /// </summary>
        [JsonPropertyName("updatedBy")]
        public string? UpdatedBy { get { return this.UpdatedByOption; } set { this.UpdatedByOption = new(value); } }

        /// <summary>
        /// Used to track the state of JourneyData
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<JourneyDataResponse?> JourneyDataOption { get; private set; }

        /// <summary>
        /// Gets or Sets JourneyData
        /// </summary>
        [JsonPropertyName("journeyData")]
        public JourneyDataResponse? JourneyData { get { return this.JourneyDataOption; } set { this.JourneyDataOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SoaResponse {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  UpdatedBy: ").Append(UpdatedBy).Append("\n");
            sb.Append("  JourneyData: ").Append(JourneyData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SoaResponse" />
    /// </summary>
    public class SoaResponseJsonConverter : JsonConverter<SoaResponse>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize UpdatedAt
        /// </summary>
        public static string UpdatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="SoaResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SoaResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<SoaStatus?> status = default;
            Option<DateTimeOffset?> createdAt = default;
            Option<string?> createdBy = default;
            Option<DateTimeOffset?> updatedAt = default;
            Option<string?> updatedBy = default;
            Option<JourneyDataResponse?> journeyData = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<SoaStatus?>(SoaStatusValueConverter.FromStringOrDefault(statusRawValue));
                            break;
                        case "createdAt":
                            createdAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "createdBy":
                            createdBy = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "updatedAt":
                            updatedAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "updatedBy":
                            updatedBy = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "journeyData":
                            journeyData = new Option<JourneyDataResponse?>(JsonSerializer.Deserialize<JourneyDataResponse>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class SoaResponse.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class SoaResponse.");

            return new SoaResponse(status, createdAt, createdBy, updatedAt, updatedBy, journeyData);
        }

        /// <summary>
        /// Serializes a <see cref="SoaResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="soaResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SoaResponse soaResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, soaResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SoaResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="soaResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SoaResponse soaResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (soaResponse.StatusOption.IsSet)
            {
                var statusRawValue = SoaStatusValueConverter.ToJsonValue(soaResponse.Status!.Value);
                writer.WriteString("status", statusRawValue);
            }
            if (soaResponse.CreatedAtOption.IsSet)
                writer.WriteString("createdAt", soaResponse.CreatedAtOption.Value!.Value.ToString(CreatedAtFormat));

            if (soaResponse.CreatedByOption.IsSet)
                if (soaResponse.CreatedByOption.Value != null)
                    writer.WriteString("createdBy", soaResponse.CreatedBy);
                else
                    writer.WriteNull("createdBy");

            if (soaResponse.UpdatedAtOption.IsSet)
                if (soaResponse.UpdatedAtOption.Value != null)
                    writer.WriteString("updatedAt", soaResponse.UpdatedAtOption.Value!.Value.ToString(UpdatedAtFormat));
                else
                    writer.WriteNull("updatedAt");

            if (soaResponse.UpdatedByOption.IsSet)
                if (soaResponse.UpdatedByOption.Value != null)
                    writer.WriteString("updatedBy", soaResponse.UpdatedBy);
                else
                    writer.WriteNull("updatedBy");

            if (soaResponse.JourneyDataOption.IsSet)
                if (soaResponse.JourneyDataOption.Value != null)
                {
                    writer.WritePropertyName("journeyData");
                    JsonSerializer.Serialize(writer, soaResponse.JourneyData, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("journeyData");
        }
    }
}
