// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// UpdateUserOrganisationRequest
    /// </summary>
    public partial class UpdateUserOrganisationRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateUserOrganisationRequest" /> class.
        /// </summary>
        /// <param name="organisation">organisation</param>
        /// <param name="role">role</param>
        /// <param name="firstName">firstName</param>
        /// <param name="lastName">lastName</param>
        /// <param name="jobTitle">jobTitle</param>
        /// <param name="preferredContactType">preferredContactType</param>
        /// <param name="landlineNumber">landlineNumber</param>
        /// <param name="contactNumberExtension">contactNumberExtension</param>
        /// <param name="mobileNumber">mobileNumber</param>
        [JsonConstructor]
        public UpdateUserOrganisationRequest(OrganisationRequest organisation, UserRole role, string firstName, string lastName, string jobTitle, Option<NullableOfPreferredContactType?> preferredContactType = default, Option<string?> landlineNumber = default, Option<string?> contactNumberExtension = default, Option<string?> mobileNumber = default)
        {
            Organisation = organisation;
            Role = role;
            FirstName = firstName;
            LastName = lastName;
            JobTitle = jobTitle;
            PreferredContactTypeOption = preferredContactType;
            LandlineNumberOption = landlineNumber;
            ContactNumberExtensionOption = contactNumberExtension;
            MobileNumberOption = mobileNumber;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        [JsonPropertyName("role")]
        public UserRole Role { get; set; }

        /// <summary>
        /// Used to track the state of PreferredContactType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<NullableOfPreferredContactType?> PreferredContactTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets PreferredContactType
        /// </summary>
        [JsonPropertyName("preferredContactType")]
        public NullableOfPreferredContactType? PreferredContactType { get { return this.PreferredContactTypeOption; } set { this.PreferredContactTypeOption = new(value); } }

        /// <summary>
        /// Gets or Sets Organisation
        /// </summary>
        [JsonPropertyName("organisation")]
        public OrganisationRequest Organisation { get; set; }

        /// <summary>
        /// Gets or Sets FirstName
        /// </summary>
        [JsonPropertyName("firstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// Gets or Sets LastName
        /// </summary>
        [JsonPropertyName("lastName")]
        public string LastName { get; set; }

        /// <summary>
        /// Gets or Sets JobTitle
        /// </summary>
        [JsonPropertyName("jobTitle")]
        public string JobTitle { get; set; }

        /// <summary>
        /// Used to track the state of LandlineNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LandlineNumberOption { get; private set; }

        /// <summary>
        /// Gets or Sets LandlineNumber
        /// </summary>
        [JsonPropertyName("landlineNumber")]
        public string? LandlineNumber { get { return this.LandlineNumberOption; } set { this.LandlineNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of ContactNumberExtension
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ContactNumberExtensionOption { get; private set; }

        /// <summary>
        /// Gets or Sets ContactNumberExtension
        /// </summary>
        [JsonPropertyName("contactNumberExtension")]
        public string? ContactNumberExtension { get { return this.ContactNumberExtensionOption; } set { this.ContactNumberExtensionOption = new(value); } }

        /// <summary>
        /// Used to track the state of MobileNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MobileNumberOption { get; private set; }

        /// <summary>
        /// Gets or Sets MobileNumber
        /// </summary>
        [JsonPropertyName("mobileNumber")]
        public string? MobileNumber { get { return this.MobileNumberOption; } set { this.MobileNumberOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateUserOrganisationRequest {\n");
            sb.Append("  Organisation: ").Append(Organisation).Append("\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  JobTitle: ").Append(JobTitle).Append("\n");
            sb.Append("  PreferredContactType: ").Append(PreferredContactType).Append("\n");
            sb.Append("  LandlineNumber: ").Append(LandlineNumber).Append("\n");
            sb.Append("  ContactNumberExtension: ").Append(ContactNumberExtension).Append("\n");
            sb.Append("  MobileNumber: ").Append(MobileNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateUserOrganisationRequest" />
    /// </summary>
    public class UpdateUserOrganisationRequestJsonConverter : JsonConverter<UpdateUserOrganisationRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="UpdateUserOrganisationRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateUserOrganisationRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<OrganisationRequest?> organisation = default;
            Option<UserRole?> role = default;
            Option<string?> firstName = default;
            Option<string?> lastName = default;
            Option<string?> jobTitle = default;
            Option<NullableOfPreferredContactType?> preferredContactType = default;
            Option<string?> landlineNumber = default;
            Option<string?> contactNumberExtension = default;
            Option<string?> mobileNumber = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "organisation":
                            organisation = new Option<OrganisationRequest?>(JsonSerializer.Deserialize<OrganisationRequest>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "role":
                            string? roleRawValue = utf8JsonReader.GetString();
                            if (roleRawValue != null)
                                role = new Option<UserRole?>(UserRoleValueConverter.FromStringOrDefault(roleRawValue));
                            break;
                        case "firstName":
                            firstName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "lastName":
                            lastName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "jobTitle":
                            jobTitle = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "preferredContactType":
                            string? preferredContactTypeRawValue = utf8JsonReader.GetString();
                            if (preferredContactTypeRawValue != null)
                                preferredContactType = new Option<NullableOfPreferredContactType?>(NullableOfPreferredContactTypeValueConverter.FromStringOrDefault(preferredContactTypeRawValue));
                            break;
                        case "landlineNumber":
                            landlineNumber = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "contactNumberExtension":
                            contactNumberExtension = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "mobileNumber":
                            mobileNumber = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!organisation.IsSet)
                throw new ArgumentException("Property is required for class UpdateUserOrganisationRequest.", nameof(organisation));

            if (!role.IsSet)
                throw new ArgumentException("Property is required for class UpdateUserOrganisationRequest.", nameof(role));

            if (!firstName.IsSet)
                throw new ArgumentException("Property is required for class UpdateUserOrganisationRequest.", nameof(firstName));

            if (!lastName.IsSet)
                throw new ArgumentException("Property is required for class UpdateUserOrganisationRequest.", nameof(lastName));

            if (!jobTitle.IsSet)
                throw new ArgumentException("Property is required for class UpdateUserOrganisationRequest.", nameof(jobTitle));

            if (organisation.IsSet && organisation.Value == null)
                throw new ArgumentNullException(nameof(organisation), "Property is not nullable for class UpdateUserOrganisationRequest.");

            if (role.IsSet && role.Value == null)
                throw new ArgumentNullException(nameof(role), "Property is not nullable for class UpdateUserOrganisationRequest.");

            if (firstName.IsSet && firstName.Value == null)
                throw new ArgumentNullException(nameof(firstName), "Property is not nullable for class UpdateUserOrganisationRequest.");

            if (lastName.IsSet && lastName.Value == null)
                throw new ArgumentNullException(nameof(lastName), "Property is not nullable for class UpdateUserOrganisationRequest.");

            if (jobTitle.IsSet && jobTitle.Value == null)
                throw new ArgumentNullException(nameof(jobTitle), "Property is not nullable for class UpdateUserOrganisationRequest.");

            return new UpdateUserOrganisationRequest(organisation.Value!, role.Value!.Value!, firstName.Value!, lastName.Value!, jobTitle.Value!, preferredContactType, landlineNumber, contactNumberExtension, mobileNumber);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateUserOrganisationRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateUserOrganisationRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateUserOrganisationRequest updateUserOrganisationRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, updateUserOrganisationRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateUserOrganisationRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateUserOrganisationRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UpdateUserOrganisationRequest updateUserOrganisationRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateUserOrganisationRequest.Organisation == null)
                throw new ArgumentNullException(nameof(updateUserOrganisationRequest.Organisation), "Property is required for class UpdateUserOrganisationRequest.");

            if (updateUserOrganisationRequest.FirstName == null)
                throw new ArgumentNullException(nameof(updateUserOrganisationRequest.FirstName), "Property is required for class UpdateUserOrganisationRequest.");

            if (updateUserOrganisationRequest.LastName == null)
                throw new ArgumentNullException(nameof(updateUserOrganisationRequest.LastName), "Property is required for class UpdateUserOrganisationRequest.");

            if (updateUserOrganisationRequest.JobTitle == null)
                throw new ArgumentNullException(nameof(updateUserOrganisationRequest.JobTitle), "Property is required for class UpdateUserOrganisationRequest.");

            writer.WritePropertyName("organisation");
            JsonSerializer.Serialize(writer, updateUserOrganisationRequest.Organisation, jsonSerializerOptions);
            var roleRawValue = UserRoleValueConverter.ToJsonValue(updateUserOrganisationRequest.Role);
            writer.WriteString("role", roleRawValue);

            writer.WriteString("firstName", updateUserOrganisationRequest.FirstName);

            writer.WriteString("lastName", updateUserOrganisationRequest.LastName);

            writer.WriteString("jobTitle", updateUserOrganisationRequest.JobTitle);

            if (updateUserOrganisationRequest.PreferredContactTypeOption.IsSet)
                if (updateUserOrganisationRequest.PreferredContactTypeOption!.Value != null)
                {
                    var preferredContactTypeRawValue = NullableOfPreferredContactTypeValueConverter.ToJsonValue(updateUserOrganisationRequest.PreferredContactTypeOption.Value!.Value);
                    writer.WriteString("preferredContactType", preferredContactTypeRawValue);
                }
                else
                    writer.WriteNull("preferredContactType");
            if (updateUserOrganisationRequest.LandlineNumberOption.IsSet)
                if (updateUserOrganisationRequest.LandlineNumberOption.Value != null)
                    writer.WriteString("landlineNumber", updateUserOrganisationRequest.LandlineNumber);
                else
                    writer.WriteNull("landlineNumber");

            if (updateUserOrganisationRequest.ContactNumberExtensionOption.IsSet)
                if (updateUserOrganisationRequest.ContactNumberExtensionOption.Value != null)
                    writer.WriteString("contactNumberExtension", updateUserOrganisationRequest.ContactNumberExtension);
                else
                    writer.WriteNull("contactNumberExtension");

            if (updateUserOrganisationRequest.MobileNumberOption.IsSet)
                if (updateUserOrganisationRequest.MobileNumberOption.Value != null)
                    writer.WriteString("mobileNumber", updateUserOrganisationRequest.MobileNumber);
                else
                    writer.WriteNull("mobileNumber");
        }
    }
}
