// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// UpdateAssessmentPlanRequest
    /// </summary>
    public partial class UpdateAssessmentPlanRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateAssessmentPlanRequest" /> class.
        /// </summary>
        /// <param name="hnId">hnId</param>
        /// <param name="phase">phase</param>
        /// <param name="updatedBy">updatedBy</param>
        /// <param name="fileName">fileName</param>
        /// <param name="s3Key">s3Key</param>
        /// <param name="stage">stage</param>
        [JsonConstructor]
        public UpdateAssessmentPlanRequest(string hnId, SoaPhase phase, string updatedBy, string fileName, string s3Key, Option<NullableOfSoaStage?> stage = default)
        {
            HnId = hnId;
            Phase = phase;
            UpdatedBy = updatedBy;
            FileName = fileName;
            S3Key = s3Key;
            StageOption = stage;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Phase
        /// </summary>
        [JsonPropertyName("phase")]
        public SoaPhase Phase { get; set; }

        /// <summary>
        /// Used to track the state of Stage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<NullableOfSoaStage?> StageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Stage
        /// </summary>
        [JsonPropertyName("stage")]
        public NullableOfSoaStage? Stage { get { return this.StageOption; } set { this.StageOption = new(value); } }

        /// <summary>
        /// Gets or Sets HnId
        /// </summary>
        [JsonPropertyName("hnId")]
        public string HnId { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedBy
        /// </summary>
        [JsonPropertyName("updatedBy")]
        public string UpdatedBy { get; set; }

        /// <summary>
        /// Gets or Sets FileName
        /// </summary>
        [JsonPropertyName("fileName")]
        public string FileName { get; set; }

        /// <summary>
        /// Gets or Sets S3Key
        /// </summary>
        [JsonPropertyName("s3Key")]
        public string S3Key { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateAssessmentPlanRequest {\n");
            sb.Append("  HnId: ").Append(HnId).Append("\n");
            sb.Append("  Phase: ").Append(Phase).Append("\n");
            sb.Append("  UpdatedBy: ").Append(UpdatedBy).Append("\n");
            sb.Append("  FileName: ").Append(FileName).Append("\n");
            sb.Append("  S3Key: ").Append(S3Key).Append("\n");
            sb.Append("  Stage: ").Append(Stage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateAssessmentPlanRequest" />
    /// </summary>
    public class UpdateAssessmentPlanRequestJsonConverter : JsonConverter<UpdateAssessmentPlanRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="UpdateAssessmentPlanRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateAssessmentPlanRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> hnId = default;
            Option<SoaPhase?> phase = default;
            Option<string?> updatedBy = default;
            Option<string?> fileName = default;
            Option<string?> s3Key = default;
            Option<NullableOfSoaStage?> stage = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "hnId":
                            hnId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "phase":
                            string? phaseRawValue = utf8JsonReader.GetString();
                            if (phaseRawValue != null)
                                phase = new Option<SoaPhase?>(SoaPhaseValueConverter.FromStringOrDefault(phaseRawValue));
                            break;
                        case "updatedBy":
                            updatedBy = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "fileName":
                            fileName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "s3Key":
                            s3Key = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "stage":
                            string? stageRawValue = utf8JsonReader.GetString();
                            if (stageRawValue != null)
                                stage = new Option<NullableOfSoaStage?>(NullableOfSoaStageValueConverter.FromStringOrDefault(stageRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!hnId.IsSet)
                throw new ArgumentException("Property is required for class UpdateAssessmentPlanRequest.", nameof(hnId));

            if (!phase.IsSet)
                throw new ArgumentException("Property is required for class UpdateAssessmentPlanRequest.", nameof(phase));

            if (!updatedBy.IsSet)
                throw new ArgumentException("Property is required for class UpdateAssessmentPlanRequest.", nameof(updatedBy));

            if (!fileName.IsSet)
                throw new ArgumentException("Property is required for class UpdateAssessmentPlanRequest.", nameof(fileName));

            if (!s3Key.IsSet)
                throw new ArgumentException("Property is required for class UpdateAssessmentPlanRequest.", nameof(s3Key));

            if (hnId.IsSet && hnId.Value == null)
                throw new ArgumentNullException(nameof(hnId), "Property is not nullable for class UpdateAssessmentPlanRequest.");

            if (phase.IsSet && phase.Value == null)
                throw new ArgumentNullException(nameof(phase), "Property is not nullable for class UpdateAssessmentPlanRequest.");

            if (updatedBy.IsSet && updatedBy.Value == null)
                throw new ArgumentNullException(nameof(updatedBy), "Property is not nullable for class UpdateAssessmentPlanRequest.");

            if (fileName.IsSet && fileName.Value == null)
                throw new ArgumentNullException(nameof(fileName), "Property is not nullable for class UpdateAssessmentPlanRequest.");

            if (s3Key.IsSet && s3Key.Value == null)
                throw new ArgumentNullException(nameof(s3Key), "Property is not nullable for class UpdateAssessmentPlanRequest.");

            return new UpdateAssessmentPlanRequest(hnId.Value!, phase.Value!.Value!, updatedBy.Value!, fileName.Value!, s3Key.Value!, stage);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateAssessmentPlanRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateAssessmentPlanRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateAssessmentPlanRequest updateAssessmentPlanRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, updateAssessmentPlanRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateAssessmentPlanRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateAssessmentPlanRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UpdateAssessmentPlanRequest updateAssessmentPlanRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateAssessmentPlanRequest.HnId == null)
                throw new ArgumentNullException(nameof(updateAssessmentPlanRequest.HnId), "Property is required for class UpdateAssessmentPlanRequest.");

            if (updateAssessmentPlanRequest.UpdatedBy == null)
                throw new ArgumentNullException(nameof(updateAssessmentPlanRequest.UpdatedBy), "Property is required for class UpdateAssessmentPlanRequest.");

            if (updateAssessmentPlanRequest.FileName == null)
                throw new ArgumentNullException(nameof(updateAssessmentPlanRequest.FileName), "Property is required for class UpdateAssessmentPlanRequest.");

            if (updateAssessmentPlanRequest.S3Key == null)
                throw new ArgumentNullException(nameof(updateAssessmentPlanRequest.S3Key), "Property is required for class UpdateAssessmentPlanRequest.");

            writer.WriteString("hnId", updateAssessmentPlanRequest.HnId);

            var phaseRawValue = SoaPhaseValueConverter.ToJsonValue(updateAssessmentPlanRequest.Phase);
            writer.WriteString("phase", phaseRawValue);

            writer.WriteString("updatedBy", updateAssessmentPlanRequest.UpdatedBy);

            writer.WriteString("fileName", updateAssessmentPlanRequest.FileName);

            writer.WriteString("s3Key", updateAssessmentPlanRequest.S3Key);

            if (updateAssessmentPlanRequest.StageOption.IsSet)
                if (updateAssessmentPlanRequest.StageOption!.Value != null)
                {
                    var stageRawValue = NullableOfSoaStageValueConverter.ToJsonValue(updateAssessmentPlanRequest.StageOption.Value!.Value);
                    writer.WriteString("stage", stageRawValue);
                }
                else
                    writer.WriteNull("stage");
        }
    }
}
