// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// UserRoleDetailResponse
    /// </summary>
    public partial class UserRoleDetailResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserRoleDetailResponse" /> class.
        /// </summary>
        /// <param name="fullName">fullName</param>
        /// <param name="userId">userId</param>
        /// <param name="emailId">emailId</param>
        /// <param name="roleDescription">roleDescription</param>
        [JsonConstructor]
        public UserRoleDetailResponse(Option<string?> fullName = default, Option<string?> userId = default, Option<string?> emailId = default, Option<string?> roleDescription = default)
        {
            FullNameOption = fullName;
            UserIdOption = userId;
            EmailIdOption = emailId;
            RoleDescriptionOption = roleDescription;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of FullName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FullNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets FullName
        /// </summary>
        [JsonPropertyName("fullName")]
        public string? FullName { get { return this.FullNameOption; } set { this.FullNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of UserId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UserIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [JsonPropertyName("userId")]
        public string? UserId { get { return this.UserIdOption; } set { this.UserIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of EmailId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EmailIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets EmailId
        /// </summary>
        [JsonPropertyName("emailId")]
        public string? EmailId { get { return this.EmailIdOption; } set { this.EmailIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of RoleDescription
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RoleDescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets RoleDescription
        /// </summary>
        [JsonPropertyName("roleDescription")]
        public string? RoleDescription { get { return this.RoleDescriptionOption; } set { this.RoleDescriptionOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserRoleDetailResponse {\n");
            sb.Append("  FullName: ").Append(FullName).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  EmailId: ").Append(EmailId).Append("\n");
            sb.Append("  RoleDescription: ").Append(RoleDescription).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UserRoleDetailResponse" />
    /// </summary>
    public class UserRoleDetailResponseJsonConverter : JsonConverter<UserRoleDetailResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="UserRoleDetailResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UserRoleDetailResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> fullName = default;
            Option<string?> userId = default;
            Option<string?> emailId = default;
            Option<string?> roleDescription = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "fullName":
                            fullName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "userId":
                            userId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "emailId":
                            emailId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "roleDescription":
                            roleDescription = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (fullName.IsSet && fullName.Value == null)
                throw new ArgumentNullException(nameof(fullName), "Property is not nullable for class UserRoleDetailResponse.");

            if (userId.IsSet && userId.Value == null)
                throw new ArgumentNullException(nameof(userId), "Property is not nullable for class UserRoleDetailResponse.");

            if (emailId.IsSet && emailId.Value == null)
                throw new ArgumentNullException(nameof(emailId), "Property is not nullable for class UserRoleDetailResponse.");

            if (roleDescription.IsSet && roleDescription.Value == null)
                throw new ArgumentNullException(nameof(roleDescription), "Property is not nullable for class UserRoleDetailResponse.");

            return new UserRoleDetailResponse(fullName, userId, emailId, roleDescription);
        }

        /// <summary>
        /// Serializes a <see cref="UserRoleDetailResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="userRoleDetailResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UserRoleDetailResponse userRoleDetailResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, userRoleDetailResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UserRoleDetailResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="userRoleDetailResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UserRoleDetailResponse userRoleDetailResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (userRoleDetailResponse.FullNameOption.IsSet && userRoleDetailResponse.FullName == null)
                throw new ArgumentNullException(nameof(userRoleDetailResponse.FullName), "Property is required for class UserRoleDetailResponse.");

            if (userRoleDetailResponse.UserIdOption.IsSet && userRoleDetailResponse.UserId == null)
                throw new ArgumentNullException(nameof(userRoleDetailResponse.UserId), "Property is required for class UserRoleDetailResponse.");

            if (userRoleDetailResponse.EmailIdOption.IsSet && userRoleDetailResponse.EmailId == null)
                throw new ArgumentNullException(nameof(userRoleDetailResponse.EmailId), "Property is required for class UserRoleDetailResponse.");

            if (userRoleDetailResponse.RoleDescriptionOption.IsSet && userRoleDetailResponse.RoleDescription == null)
                throw new ArgumentNullException(nameof(userRoleDetailResponse.RoleDescription), "Property is required for class UserRoleDetailResponse.");

            if (userRoleDetailResponse.FullNameOption.IsSet)
                writer.WriteString("fullName", userRoleDetailResponse.FullName);

            if (userRoleDetailResponse.UserIdOption.IsSet)
                writer.WriteString("userId", userRoleDetailResponse.UserId);

            if (userRoleDetailResponse.EmailIdOption.IsSet)
                writer.WriteString("emailId", userRoleDetailResponse.EmailId);

            if (userRoleDetailResponse.RoleDescriptionOption.IsSet)
                writer.WriteString("roleDescription", userRoleDetailResponse.RoleDescription);
        }
    }
}
