// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using HNTAS.Api.Client.Client;
using HNTAS.Api.Client.Model;
using System.Diagnostics.CodeAnalysis;

namespace HNTAS.Api.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface IAssignedAssessorApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        AssignedAssessorApiEvents Events { get; }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="assignedAssessorRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IApiAssignedAssessorAssignedAssessorGetApiResponse"/>&gt;</returns>
        Task<IApiAssignedAssessorAssignedAssessorGetApiResponse> ApiAssignedAssessorAssignedAssessorGetAsync(AssignedAssessorRequest assignedAssessorRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="assignedAssessorRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IApiAssignedAssessorAssignedAssessorGetApiResponse"/>?&gt;</returns>
        Task<IApiAssignedAssessorAssignedAssessorGetApiResponse?> ApiAssignedAssessorAssignedAssessorGetOrDefaultAsync(AssignedAssessorRequest assignedAssessorRequest, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="IApiAssignedAssessorAssignedAssessorGetApiResponse"/>
    /// </summary>
    public interface IApiAssignedAssessorAssignedAssessorGetApiResponse : HNTAS.Api.Client.Client.IApiResponse, IOk<HNTAS.Api.Client.Model.AssignedAssessorResponse?>, INotFound<HNTAS.Api.Client.Model.ProblemDetails?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 404 NotFound
        /// </summary>
        /// <returns></returns>
        bool IsNotFound { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class AssignedAssessorApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnApiAssignedAssessorAssignedAssessorGet;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorApiAssignedAssessorAssignedAssessorGet;

        internal void ExecuteOnApiAssignedAssessorAssignedAssessorGet(AssignedAssessorApi.ApiAssignedAssessorAssignedAssessorGetApiResponse apiResponse)
        {
            OnApiAssignedAssessorAssignedAssessorGet?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorApiAssignedAssessorAssignedAssessorGet(Exception exception)
        {
            OnErrorApiAssignedAssessorAssignedAssessorGet?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class AssignedAssessorApi : IAssignedAssessorApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger factory
        /// </summary>
        public ILoggerFactory LoggerFactory { get; }

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<AssignedAssessorApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public AssignedAssessorApiEvents Events { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="AssignedAssessorApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AssignedAssessorApi(ILogger<AssignedAssessorApi> logger, ILoggerFactory loggerFactory, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, AssignedAssessorApiEvents assignedAssessorApiEvents)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            LoggerFactory = loggerFactory;
            Logger = LoggerFactory.CreateLogger<AssignedAssessorApi>();
            HttpClient = httpClient;
            Events = assignedAssessorApiEvents;
        }

        partial void FormatApiAssignedAssessorAssignedAssessorGet(AssignedAssessorRequest assignedAssessorRequest);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="assignedAssessorRequest"></param>
        /// <returns></returns>
        private void ValidateApiAssignedAssessorAssignedAssessorGet(AssignedAssessorRequest assignedAssessorRequest)
        {
            if (assignedAssessorRequest == null)
                throw new ArgumentNullException(nameof(assignedAssessorRequest));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="assignedAssessorRequest"></param>
        private void AfterApiAssignedAssessorAssignedAssessorGetDefaultImplementation(IApiAssignedAssessorAssignedAssessorGetApiResponse apiResponseLocalVar, AssignedAssessorRequest assignedAssessorRequest)
        {
            bool suppressDefaultLog = false;
            AfterApiAssignedAssessorAssignedAssessorGet(ref suppressDefaultLog, apiResponseLocalVar, assignedAssessorRequest);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="assignedAssessorRequest"></param>
        partial void AfterApiAssignedAssessorAssignedAssessorGet(ref bool suppressDefaultLog, IApiAssignedAssessorAssignedAssessorGetApiResponse apiResponseLocalVar, AssignedAssessorRequest assignedAssessorRequest);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="assignedAssessorRequest"></param>
        private void OnErrorApiAssignedAssessorAssignedAssessorGetDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, AssignedAssessorRequest assignedAssessorRequest)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorApiAssignedAssessorAssignedAssessorGet(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, assignedAssessorRequest);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="assignedAssessorRequest"></param>
        partial void OnErrorApiAssignedAssessorAssignedAssessorGet(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, AssignedAssessorRequest assignedAssessorRequest);

        /// <summary>
        ///  
        /// </summary>
        /// <param name="assignedAssessorRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IApiAssignedAssessorAssignedAssessorGetApiResponse"/>&gt;</returns>
        public async Task<IApiAssignedAssessorAssignedAssessorGetApiResponse?> ApiAssignedAssessorAssignedAssessorGetOrDefaultAsync(AssignedAssessorRequest assignedAssessorRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await ApiAssignedAssessorAssignedAssessorGetAsync(assignedAssessorRequest, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="assignedAssessorRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IApiAssignedAssessorAssignedAssessorGetApiResponse"/>&gt;</returns>
        public async Task<IApiAssignedAssessorAssignedAssessorGetApiResponse> ApiAssignedAssessorAssignedAssessorGetAsync(AssignedAssessorRequest assignedAssessorRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateApiAssignedAssessorAssignedAssessorGet(assignedAssessorRequest);

                FormatApiAssignedAssessorAssignedAssessorGet(assignedAssessorRequest);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/api/AssignedAssessor/assigned-assessor"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/api/AssignedAssessor/assigned-assessor");

                    httpRequestMessageLocalVar.Content = (assignedAssessorRequest as object) is System.IO.Stream stream
                        ? httpRequestMessageLocalVar.Content = new StreamContent(stream)
                        : httpRequestMessageLocalVar.Content = new StringContent(JsonSerializer.Serialize(assignedAssessorRequest, _jsonSerializerOptions));

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] contentTypes = new string[] {
                        "application/json",
                        "text/json",
                        "application/*+json"
                    };

                    string? contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    string[] acceptLocalVars = new string[] {
                        "text/plain",
                        "application/json",
                        "text/json"
                    };

                    string? acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<ApiAssignedAssessorAssignedAssessorGetApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<ApiAssignedAssessorAssignedAssessorGetApiResponse>();
                        ApiAssignedAssessorAssignedAssessorGetApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/api/AssignedAssessor/assigned-assessor", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterApiAssignedAssessorAssignedAssessorGetDefaultImplementation(apiResponseLocalVar, assignedAssessorRequest);

                        Events.ExecuteOnApiAssignedAssessorAssignedAssessorGet(apiResponseLocalVar);

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorApiAssignedAssessorAssignedAssessorGetDefaultImplementation(e, "/api/AssignedAssessor/assigned-assessor", uriBuilderLocalVar.Path, assignedAssessorRequest);
                Events.ExecuteOnErrorApiAssignedAssessorAssignedAssessorGet(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="ApiAssignedAssessorAssignedAssessorGetApiResponse"/>
        /// </summary>
        public partial class ApiAssignedAssessorAssignedAssessorGetApiResponse : HNTAS.Api.Client.Client.ApiResponse, IApiAssignedAssessorAssignedAssessorGetApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<ApiAssignedAssessorAssignedAssessorGetApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="ApiAssignedAssessorAssignedAssessorGetApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ApiAssignedAssessorAssignedAssessorGetApiResponse(ILogger<ApiAssignedAssessorAssignedAssessorGetApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="ApiAssignedAssessorAssignedAssessorGetApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ApiAssignedAssessorAssignedAssessorGetApiResponse(ILogger<ApiAssignedAssessorAssignedAssessorGetApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public HNTAS.Api.Client.Model.AssignedAssessorResponse? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<HNTAS.Api.Client.Model.AssignedAssessorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out HNTAS.Api.Client.Model.AssignedAssessorResponse? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public bool IsNotFound => 404 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public HNTAS.Api.Client.Model.ProblemDetails? NotFound()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsNotFound
                    ? System.Text.Json.JsonSerializer.Deserialize<HNTAS.Api.Client.Model.ProblemDetails>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryNotFound([NotNullWhen(true)]out HNTAS.Api.Client.Model.ProblemDetails? result)
            {
                result = null;

                try
                {
                    result = NotFound();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)404);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
