/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using HNTAS.Api.Client.Api;
using HNTAS.Api.Client.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace HNTAS.Api.Client.Test.Api
{
    /// <summary>
    ///  Class for testing ArmsDashboardApi
    /// </summary>
    public sealed class ArmsDashboardApiTests : ApiTestsBase
    {
        private readonly IArmsDashboardApi _instance;

        public ArmsDashboardApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IArmsDashboardApi>();
        }

        /// <summary>
        /// Test ApiArmsDashboardGetKpiNetworkDetailsGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiArmsDashboardGetKpiNetworkDetailsGetAsyncTest()
        {
            Client.Option<string> submissionId = default!;
            Client.Option<string> statusFilter = default!;
            Client.Option<string> typeFilter = default!;
            Client.Option<int> page = default!;
            var response = await _instance.ApiArmsDashboardGetKpiNetworkDetailsGetAsync(submissionId, statusFilter, typeFilter, page);
            var model = response.Ok();
            Assert.IsType<HeatNetworkDetailsResponse>(model);
        }

        /// <summary>
        /// Test ApiArmsDashboardGetKpiNetworksByRpUserGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiArmsDashboardGetKpiNetworksByRpUserGetAsyncTest()
        {
            Client.Option<string> userId = default!;
            Client.Option<int> month = default!;
            Client.Option<int> year = default!;
            Client.Option<int> pageNumber = default!;
            var response = await _instance.ApiArmsDashboardGetKpiNetworksByRpUserGetAsync(userId, month, year, pageNumber);
            var model = response.Ok();
            Assert.IsType<HeatNetworkDashboardResponse>(model);
        }

        /// <summary>
        /// Test ApiArmsDashboardSubmissionIdHistoryGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiArmsDashboardSubmissionIdHistoryGetAsyncTest()
        {
            string submissionId = default!;
            var response = await _instance.ApiArmsDashboardSubmissionIdHistoryGetAsync(submissionId);
            var model = response.Ok();
            Assert.IsType<List<KpiHistoryResponse>>(model);
        }
    }
}
