/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using HNTAS.Api.Client.Api;
using HNTAS.Api.Client.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace HNTAS.Api.Client.Test.Api
{
    /// <summary>
    ///  Class for testing SOAApi
    /// </summary>
    public sealed class SOAApiTests : ApiTestsBase
    {
        private readonly ISOAApi _instance;

        public SOAApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<ISOAApi>();
        }

        /// <summary>
        /// Test ApiSOAConnectionsPatch
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiSOAConnectionsPatchAsyncTest()
        {
            UpdateConnectionsRequest updateConnectionsRequest = default!;
            await _instance.ApiSOAConnectionsPatchAsync(updateConnectionsRequest);
        }

        /// <summary>
        /// Test ApiSOACreatePost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiSOACreatePostAsyncTest()
        {
            Client.Option<string> hnId = default!;
            Client.Option<string> createdBy = default!;
            var response = await _instance.ApiSOACreatePostAsync(hnId, createdBy);
            var model = response.Ok();
            Assert.IsType<Soa2>(model);
        }

        /// <summary>
        /// Test ApiSOADocumentUpdatePatch
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiSOADocumentUpdatePatchAsyncTest()
        {
            UpdateDocumentRequest updateDocumentRequest = default!;
            await _instance.ApiSOADocumentUpdatePatchAsync(updateDocumentRequest);
        }

        /// <summary>
        /// Test ApiSOAElementDocumentsPatch
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiSOAElementDocumentsPatchAsyncTest()
        {
            UpdateElementDocumentsRequest updateElementDocumentsRequest = default!;
            await _instance.ApiSOAElementDocumentsPatchAsync(updateElementDocumentsRequest);
        }

        /// <summary>
        /// Test ApiSOAElementLocationsPatch
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiSOAElementLocationsPatchAsyncTest()
        {
            UpdateElementLocationsRequest updateElementLocationsRequest = default!;
            await _instance.ApiSOAElementLocationsPatchAsync(updateElementLocationsRequest);
        }

        /// <summary>
        /// Test ApiSOAHeatNetworkHnIdGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiSOAHeatNetworkHnIdGetAsyncTest()
        {
            string hnId = default!;
            var response = await _instance.ApiSOAHeatNetworkHnIdGetAsync(hnId);
            var model = response.Ok();
            Assert.IsType<Soa2>(model);
        }

        /// <summary>
        /// Test ApiSOAHnIdDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiSOAHnIdDeleteAsyncTest()
        {
            string hnId = default!;
            await _instance.ApiSOAHnIdDeleteAsync(hnId);
        }

        /// <summary>
        /// Test ApiSOANetworkElementsPatch
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiSOANetworkElementsPatchAsyncTest()
        {
            List<HeatNetworkElement> heatNetworkElement = default!;
            Client.Option<string> hnId = default!;
            Client.Option<string> updatedBy = default!;
            await _instance.ApiSOANetworkElementsPatchAsync(heatNetworkElement, hnId, updatedBy);
        }

        /// <summary>
        /// Test ApiSOANetworkTypePatch
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiSOANetworkTypePatchAsyncTest()
        {
            NetworkTypeSelection2 networkTypeSelection2 = default!;
            Client.Option<string> hnId = default!;
            Client.Option<string> updatedBy = default!;
            await _instance.ApiSOANetworkTypePatchAsync(networkTypeSelection2, hnId, updatedBy);
        }

        /// <summary>
        /// Test ApiSOASendAssessorAssessmentEmailPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiSOASendAssessorAssessmentEmailPostAsyncTest()
        {
            string hnName = default!;
            string hnId = default!;
            string assessmentResult = default!;
            await _instance.ApiSOASendAssessorAssessmentEmailPostAsync(hnName, hnId, assessmentResult);
        }

        /// <summary>
        /// Test ApiSOASendCertificationCompleteEmailPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiSOASendCertificationCompleteEmailPostAsyncTest()
        {
            string hnName = default!;
            string hnId = default!;
            await _instance.ApiSOASendCertificationCompleteEmailPostAsync(hnName, hnId);
        }

        /// <summary>
        /// Test ApiSOASoaAssignAssessorPatch
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiSOASoaAssignAssessorPatchAsyncTest()
        {
            ElementSoaAssignAssessorRequest elementSoaAssignAssessorRequest = default!;
            await _instance.ApiSOASoaAssignAssessorPatchAsync(elementSoaAssignAssessorRequest);
        }

        /// <summary>
        /// Test ApiSOAUpdateSoaStatusPatch
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiSOAUpdateSoaStatusPatchAsyncTest()
        {
            ElementSoaStatusUpdateRequest elementSoaStatusUpdateRequest = default!;
            await _instance.ApiSOAUpdateSoaStatusPatchAsync(elementSoaStatusUpdateRequest);
        }

        /// <summary>
        /// Test ApiSOAUpdateSoaStatusPut
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiSOAUpdateSoaStatusPutAsyncTest()
        {
            UpdateSoaStatusRequest updateSoaStatusRequest = default!;
            await _instance.ApiSOAUpdateSoaStatusPutAsync(updateSoaStatusRequest);
        }
    }
}
