/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using HNTAS.Api.Client.Api;
using HNTAS.Api.Client.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace HNTAS.Api.Client.Test.Api
{
    /// <summary>
<<<<<<<< HEAD:HNTAS/HNTAS.Api.Client/src/HNTAS.Api.Client.Test/Api/AssessorApiTests.cs
    ///  Class for testing AssessorApi
    /// </summary>
    public sealed class AssessorApiTests : ApiTestsBase
    {
        private readonly IAssessorApi _instance;

        public AssessorApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IAssessorApi>();
        }

        /// <summary>
        /// Test ApiAssessorSearchGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiAssessorSearchGetAsyncTest()
        {
            Client.Option<string> q = default!;
            var response = await _instance.ApiAssessorSearchGetAsync(q);
            var model = response.Ok();
            Assert.IsType<List<AssessorSearchResult>>(model);
========
    ///  Class for testing TestApi
    /// </summary>
    public sealed class TestApiTests : ApiTestsBase
    {
        private readonly ITestApi _instance;

        public TestApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<ITestApi>();
        }

        /// <summary>
        /// Test ApiTestTestDocumentdbConnectionGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiTestTestDocumentdbConnectionGetAsyncTest()
        {
            await _instance.ApiTestTestDocumentdbConnectionGetAsync();
>>>>>>>> f05028e74d3945e17c6e4dc0a284b52f6b8ade65:HNTAS/HNTAS.Api.Client/src/HNTAS.Api.Client.Test/Api/TestApiTests.cs
        }
    }
}
